export const cardDetails = [
  {
    id: "card1",
    title: "Elegant Vows",
    cat: "Hindu",
    price: 20,
    des: "Elegant ivory card with gold foil lettering and intricate lace patterns.",
    path: "https://i.ibb.co/NFhN5J1/card1.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card2",
    title: "Joyful Union",
    cat: "Hindu",
    price: 15,
    des: "Rustic kraft paper invitation with hand-drawn floral accents.",
    path: "https://i.ibb.co/5r0HWLx/card2.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card3",
    title: "Sacred Bond",
    cat: "Hindu",
    price: 10,
    des: "Modern minimalist design with clean lines and a monochrome color scheme.",
    path: "https://i.ibb.co/y8MjkrY/card3.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card4",
    title: "Timeless Love",
    cat: "Hindu",
    price: 13,
    des: "Vintage-inspired card with delicate watercolor florals and cursive script.",
    path: "https://i.ibb.co/vVBSW0k/card5-2.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card5",
    title: "Blissful Beginnings",
    cat: "Hindu",
    price: 46,
    des: "Chic black and white invitation with bold typography and geometric shapes.",
    path: "https://i.ibb.co/RBbfwLz/card5.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card6",
    title: "Pure Romance",
    cat: "Hindu",
    price: 14,
    des: "Classic navy and gold invitation with a timeless monogram.",
    path: "https://i.ibb.co/By8wF1J/card6.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card7",
    title: "Eternal Bliss",
    cat: "Hindu",
    price: 19,
    des: "Whimsical card featuring watercolor illustrations and playful fonts.",
    path: "https://i.ibb.co/4pBdt7r/card7.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card8",
    title: "Serene Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Luxurious card with velvet touch finish and gold embossing.",
    path: "https://i.ibb.co/nCvLf7z/card9.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card9",
    title: "Classic Love",
    cat: "Hindu",
    price: 50,
    des: "Romantic blush pink invitation with rose gold foil details.",
    path: "https://i.ibb.co/khWKkP2/card10.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card10",
    title: "Heartfelt Union",
    cat: "Hindu",
    price: 50,
    des: "Tropical-themed card with vibrant palm leaves and exotic flowers",
    path: "https://i.ibb.co/tK0TvKC/card11.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card11",
    title: "Divine Love",
    cat: "Hindu",
    price: 50,
    des: "Elegant emerald green invitation with gold accents and a satin ribbon.",
    path: "https://i.ibb.co/crTmJtY/card12.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card12",
    title: "Graceful Union",
    cat: "Hindu",
    price: 50,
    des: "Art deco-inspired design with metallic accents and bold patterns.",
    path: "https://i.ibb.co/crstXWq/card13.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card13",
    title: "True Love",
    cat: "Hindu",
    price: 50,
    des: "Simple kraft paper card with twine and a wax seal",
    path: "https://i.ibb.co/j4mBZzb/card14.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card14",
    title: "Regal Wedding",
    cat: "Hindu",
    price: 50,
    des: "Nautical-themed invitation with navy stripes and anchor motifs.",
    path: "https://i.ibb.co/w6bJYth/card15.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card15",
    title: "Happy Hearts",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated marble design with gold foil details.",
    path: "https://i.ibb.co/fXz3cwt/card16.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card16",
    title: "Sweet Vows",
    cat: "Hindu",
    price: 50,
    des: "Bohemian-style card with dreamcatcher illustrations and earthy tones.",
    path: "https://i.ibb.co/Fgbrq4x/card16-2.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card17",
    title: " Beautiful Beginnings",
    cat: "Hindu",
    price: 50,
    des: "Glamorous glittery gold invitation with a classic script font.",
    path: "https://i.ibb.co/SmHVPXV/card17.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card18",
    title: "Cherished Moments",
    cat: "Hindu",
    price: 50,
    des: "Eco-friendly card made from recycled paper with botanical prints.",
    path: "https://i.ibb.co/5Lyc1v0/card18.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card19",
    title: "Precious Love",
    cat: "Hindu",
    price: 50,
    des: "Fairy tale-inspired design with enchanted forest illustrations.",
    path: "https://i.ibb.co/tzCcrpq/card19.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card20",
    title: "Love Knot",
    cat: "Hindu",
    price: 50,
    des: "Elegant cream and gold invitation with intricate laser-cut details.",
    path: "https://i.ibb.co/cDNLWgr/card20.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card21",
    title: "Serene Vows",
    cat: "Hindu",
    price: 50,
    des: "Floral watercolor card with a delicate border and elegant script.",
    path: "https://i.ibb.co/Vt347b5/card21.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card22",
    title: "Blissful Union",
    cat: "Hindu",
    price: 50,
    des: "Modern acrylic invitation with sleek typography.",
    path: "https://i.ibb.co/Rpp6C92/card22.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card23",
    title: "Perfect Pair",
    cat: "Hindu",
    price: 50,
    des: "Rustic wood veneer card with engraved details.",
    path: "https://i.ibb.co/WWztyDn/card24.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card24",
    title: " Simple Elegance",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated grey and silver invitation with a minimalist design.",
    path: "https://i.ibb.co/RpLmqkF/card23.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card25",
    title: " Pure Joy",
    cat: "Hindu",
    price: 50,
    des: "Tropical destination wedding invitation with vibrant hibiscus flowers.",
    path: "https://i.ibb.co/Qjp1Z7G/card25.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card26",
    title: "Golden Moments",
    cat: "Hindu",
    price: 50,
    des: "Whimsical balloon-themed card with colorful illustrations.",
    path: "https://i.ibb.co/GCkLJZd/card27.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card27",
    title: "Sacred Promise",
    cat: "Hindu",
    price: 50,
    des: "Vintage postcard-style invitation with a nostalgic feel.",
    path: "https://i.ibb.co/dgWvzqk/card26.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card28",
    title: " Lovely Bond",
    cat: "Hindu",
    price: 50,
    des: "Elegant pearl-finished card with lace patterns and satin bow.",
    path: "https://i.ibb.co/4KfPxJh/card28.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card29",
    title: "Joyous Journey",
    cat: "Hindu",
    price: 50,
    des: "Bold red and gold invitation with a traditional Asian design.",
    path: "https://i.ibb.co/9YB7wMY/card29.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card30",
    title: "Sweet Love",
    cat: "Hindu",
    price: 50,
    des: "Charming cottage-themed card with hand-painted flowers.",
    path: "https://i.ibb.co/R3fK1r3/card30.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card31",
    title: "Radiant Hearts",
    cat: "Hindu",
    price: 50,
    des: "Luxurious velvet card with gold foil stamping.",
    path: "https://i.ibb.co/fXx26Hp/card31.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card32",
    title: "Enchanted Love",
    cat: "Hindu",
    price: 50,
    des: "Minimalist kraft paper invitation with calligraphy.",
    path: "https://i.ibb.co/hBN889q/card32.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card33",
    title: "Elegant Affair",
    cat: "Hindu",
    price: 50,
    des: "Elegant scroll invitation with gold accents and a ribbon tie.",
    path: "https://i.ibb.co/c12NpWT/card33.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card34",
    title: "Love’s Embrace",
    cat: "Hindu",
    price: 50,
    des: "Rustic burlap card with lace and twine details.",
    path: "https://i.ibb.co/cx4XWpH/card34.png",
    path2: "",
    path3: "",
  },
  {
    id: "card35",
    title: " Dreamy Vows",
    cat: "Hindu",
    price: 50,
    des: "Classic black-tie invitation with sleek black and white design.",
    path: "https://i.ibb.co/rFH3wD0/card35.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card36",
    title: "Serene Union",
    cat: "Hindu",
    price: 50,
    des: "Nautical navy and white card with anchor details.",
    path: "https://i.ibb.co/GdG21MH/card36.png",
    path2: "",
    path3: "",
  },
  {
    id: "card37",
    title: "Charming Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Botanical-themed invitation with lush greenery illustrations.",
    path: "https://i.ibb.co/1K2yNJD/card37.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card38",
    title: "Elegant Love",
    cat: "Hindu",
    price: 50,
    des: "Vintage lace overlay card with pearl accents.",
    path: "https://i.ibb.co/xfNHGXS/card38.png",
    path2: "",
    path3: "",
  },
  {
    id: "card39",
    title: "Heartfelt Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Modern geometric design with gold foil and bold typography.",
    path: "https://i.ibb.co/ryPgfJt/card39.png",
    path2: "",
    path3: "",
  },
  {
    id: "card40",
    title: " Regal Union",
    cat: "Hindu",
    price: 50,
    des: "Floral laser-cut invitation with a blush pink ribbon.",
    path: "https://i.ibb.co/tpGJJz1/card40.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card41",
    title: "Sacred Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Elegant damask pattern card with silver foil.",
    path: "https://i.ibb.co/FgN06HL/card43.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card42",
    title: "Joyful Hearts",
    cat: "Hindu",
    price: 50,
    des: "Whimsical garden-themed card with colorful floral illustrations.",
    path: "https://i.ibb.co/5KGdp2F/card41.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card43",
    title: "Blissful Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated navy and gold invitation with a monogrammed seal.",
    path: "https://i.ibb.co/7RwqTSB/card42.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card44",
    title: "Lovely Vows",
    cat: "Hindu",
    price: 50,
    des: "Rustic kraft paper card with botanical prints and twine.",
    path: "https://i.ibb.co/bF8Jb8r/card45.png",
    path2: "",
    path3: "",
  },
  {
    id: "card45",
    title: " Pure Bliss",
    cat: "Hindu",
    price: 50,
    des: "Glamorous glitter invitation with elegant script font.",
    path: "https://i.ibb.co/T8X2c4w/card46.png",
    path2: "",
    path3: "",
  },
  {
    id: "card46",
    title: "Love’s Journey",
    cat: "Hindu",
    price: 50,
    des: "Minimalist white card with gold foil lettering.",
    path: "https://i.ibb.co/T8X2c4w/card46.png",
    path2: "",
    path3: "",
  },
  {
    id: "card47",
    title: "Happy Together",
    cat: "Hindu",
    price: 50,
    des: "Bohemian-inspired design with dreamcatcher and feathers.",
    path: "https://i.ibb.co/JRrXSTM/card47.png",
    path2: "",
    path3: "",
  },
  {
    id: "card48",
    title: "Sweet Harmony",
    cat: "Hindu",
    price: 50,
    des: "Rustic woodgrain invitation with delicate lace details.",
    path: "https://i.ibb.co/6nsvb77/card48.png",
    path2: "",
    path3: "",
  },
  {
    id: "card49",
    title: "Graceful Vows",
    cat: "Hindu",
    price: 50,
    des: "Modern typography-focused design with a monochrome palette.",
    path: "https://i.ibb.co/rpkLyVk/card49.png",
    path2: "",
    path3: "",
  },
  {
    id: "card50",
    title: "Eternal Love",
    cat: "Hindu",
    price: 50,
    des: "Chic marble card with rose gold accents.",
    path: "https://i.ibb.co/XZxTsCQ/card50.png",
    path2: "",
    path3: "",
  },
  {
    id: "card51",
    title: "Pure Union",
    cat: "Hindu",
    price: 50,
    des: "Vintage-inspired card with pastel florals and cursive script.",
    path: "https://i.ibb.co/3N9Bry6/card51.png",
    path2: "",
    path3: "",
  },
  {
    id: "card52",
    title: "Joyful Moments",
    cat: "Hindu",
    price: 50,
    des: "Elegant pearl-finished invitation with embossed patterns.",
    path: "https://i.ibb.co/MncN3r1/card53.png",
    path2: "",
    path3: "",
  },
  {
    id: "card53",
    title: "Lovely Together",
    cat: "Hindu",
    price: 50,
    des: "Nautical-themed card with stripes and rope details.",
    path: "https://i.ibb.co/xMHGQpR/card55.png",
    path2: "",
    path3: "",
  },
  {
    id: "card54",
    title: "Heartfelt Vows",
    cat: "Hindu",
    price: 50,
    des: "Floral watercolor invitation with a soft, romantic feel.",
    path: "https://i.ibb.co/ySvS55L/card56.png",
    path2: "",
    path3: "",
  },
  {
    id: "card55",
    title: "Sacred Hearts",
    cat: "Hindu",
    price: 50,
    des: "Luxurious velvet card with gold foil and satin ribbon.",
    path: "https://i.ibb.co/t3GJHt0/card57.png",
    path2: "",
    path3: "",
  },
  {
    id: "card56",
    title: "Blissful Together",
    cat: "Hindu",
    price: -1,
    des: "Rustic kraft paper card with hand-drawn illustrations.",
    path: "https://i.ibb.co/b15yjHm/card58.png",
    path2: "",
    path3: "",
  },
  {
    id: "card57",
    title: "Elegant Union",
    cat: "Hindu",
    price: 50,
    des: "Modern acrylic invitation with sleek, transparent design.",
    path: "https://i.ibb.co/K5JJbsp/card59.png",
    path2: "",
    path3: "",
  },
  {
    id: "card58",
    title: "True Joy",
    cat: "Hindu",
    price: 50,
    des: "Botanical-themed card with lush greenery and elegant script.",
    path: "https://i.ibb.co/VSL0hv7/card60.png",
    path2: "",
    path3: "",
  },
  {
    id: "card59",
    title: "Radiant Union",
    cat: "Hindu",
    price: 50,
    des: "Chic black and gold invitation with a sophisticated feel.",
    path: "https://i.ibb.co/s2MQKNc/card61.png",
    path2: "",
    path3: "",
  },
  {
    id: "card60",
    title: " Enchanted Hearts",
    cat: "Hindu",
    price: 50,
    des: "Whimsical garden party-themed card with colorful illustrations.",
    path: "https://i.ibb.co/t3N28hr/card62.png",
    path2: "",
    path3: "",
  },
  {
    id: "card61",
    title: "Charming Love",
    cat: "Hindu",
    price: 50,
    des: "Classic cream and gold invitation with a timeless design.",
    path: "https://i.ibb.co/Kyp6R7R/card63.png",
    path2: "",
    path3: "",
  },
  {
    id: "card62",
    title: "Lovely Moments",
    cat: "Hindu",
    price: 50,
    des: "Vintage lace overlay card with delicate details.",
    path: "https://i.ibb.co/7XNPwrd/card64.png",
    path2: "",
    path3: "",
  },
  {
    id: "card63",
    title: "Joyous Union",
    cat: "Hindu",
    price: 50,
    des: "Minimalist kraft paper invitation with simple typography.",
    path: "https://i.ibb.co/JpF5T2r/card65.png",
    path2: "",
    path3: "",
  },
  {
    id: "card64",
    title: " Pure Vows",
    cat: "Hindu",
    price: 50,
    des: "Elegant damask pattern card with silver foil accents.",
    path: "https://i.ibb.co/3dF23bY/card66.png",
    path2: "",
    path3: "",
  },
  {
    id: "card65",
    title: "Sweet Moments",
    cat: "Hindu",
    price: 50,
    des: "Rustic burlap and lace invitation with twine bow.",
    path: "https://i.ibb.co/tJxt89f/card67.png",
    path2: "",
    path3: "",
  },
  {
    id: "card66",
    title: "Heartfelt Love",
    cat: "Hindu",
    price: 50,
    des: "Glamorous glitter invitation with bold gold accents.",
    path: "https://i.ibb.co/4PD9Ynv/card68.png",
    path2: "",
    path3: "",
  },
  {
    id: "card129",
    title: " Sacred Bliss",
    cat: "Hindu",
    price: 50,
    des: "Modern monochrome design with clean lines and sleek typography.",
    path: "https://i.ibb.co/5v9SJnv/card69.png",
    path2: "",
    path3: "",
  },
  {
    id: "card67",
    title: "Elegant Together",
    cat: "Hindu",
    price: 50,
    des: "Floral watercolor card with soft, pastel hues.",
    path: "https://i.ibb.co/Gd3sx71/card70.png",
    path2: "",
    path3: "",
  },
  {
    id: "card68",
    title: " Joyful Promise",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated navy and silver invitation with a monogram.",
    path: "https://i.ibb.co/YtPb89T/card71.png",
    path2: "",
    path3: "",
  },
  {
    id: "card69",
    title: "Dreamy Hearts",
    cat: "Hindu",
    price: 50,
    des: "Botanical-themed card with hand-drawn illustrations and earthy tones.",
    path: "https://i.ibb.co/Ws11mVm/card72.png",
    path2: "",
    path3: "",
  },
  {
    id: "card70",
    title: ". Love’s Harmony",
    cat: "Hindu",
    price: 50,
    des: "Vintage-inspired postcard invitation with a nostalgic design.",
    path: "https://i.ibb.co/DwFfhYg/card73.png",
    path2: "",
    path3: "",
  },
  {
    id: "card71",
    title: " Graceful Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Chic marble card with gold foil and elegant script.",
    path: "https://i.ibb.co/kgjjHmr/card75.png",
    path2: "",
    path3: "",
  },
  {
    id: "card72",
    title: "Pure Together",
    cat: "Hindu",
    price: 50,
    des: "Rustic wood veneer invitation with engraved details.",
    path: "https://i.ibb.co/6wnsRzD/card76.png",
    path2: "",
    path3: "",
  },
  {
    id: "card73",
    title: "Happy Vows",
    cat: "Hindu",
    price: 50,
    des: "Modern acrylic card with a minimalist design",
    path: "https://i.ibb.co/5cJJTfg/card77.png",
    path2: "",
    path3: "",
  },
  {
    id: "card74",
    title: ". Radiant Bliss",
    cat: "Hindu",
    price: 50,
    des: "Whimsical balloon-themed invitation with playful illustrations.",
    path: "https://i.ibb.co/Pzmt5T9/card78.png",
    path2: "",
    path3: "",
  },
  {
    id: "card75",
    title: "Serene Hearts",
    cat: "Hindu",
    price: 50,
    des: "Elegant pearl-finished card with intricate lace patterns.",
    path: "https://i.ibb.co/w7b4ndh/card79.png",
    path2: "",
    path3: "",
  },
  {
    id: "card76",
    title: "Charming Vows",
    cat: "Hindu",
    price: 50,
    des: "Nautical-themed invitation with navy stripes and anchor motifs.",
    path: "https://i.ibb.co/P4SsVjk/card80.png",
    path2: "",
    path3: "",
  },
  {
    id: "card77",
    title: "Lovely Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Floral watercolor card with a delicate border and cursive script.",
    path: "https://i.ibb.co/fphHPKm/card81.png",
    path2: "",
    path3: "",
  },
  {
    id: "card78",
    title: "Joyous Promise",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated black and white design with bold typography.",
    path: "https://i.ibb.co/Thqj7nF/card82.png",
    path2: "",
    path3: "",
  },
  {
    id: "card79",
    title: "Heartfelt Union",
    cat: "Hindu",
    price: 50,
    des: "Vintage lace overlay card with pearl accents.",
    path: "https://i.ibb.co/kQdHgnG/card83.png",
    path2: "",
    path3: "",
  },
  {
    id: "card80",
    title: "Blissful Love",
    cat: "Hindu",
    price: 50,
    des: "Rustic kraft paper invitation with botanical prints and twine.",
    path: "https://i.ibb.co/hHp9Qtm/card84.png",
    path2: "",
    path3: "",
  },
  {
    id: "card81",
    title: "Elegant Moments",
    cat: "Hindu",
    price: 50,
    des: "Glamorous glitter invitation with elegant gold foil.",
    path: "https://i.ibb.co/74Kt4bN/card85.png",
    path2: "",
    path3: "",
  },
  {
    id: "card82",
    title: "True Together",
    cat: "Hindu",
    price: 50,
    des: "Minimalist white card with sleek, modern typography",
    path: "https://i.ibb.co/hZF9psH/card86.png",
    path2: "",
    path3: "",
  },
  {
    id: "card83",
    title: "Sacred Joy",
    cat: "Hindu",
    price: 50,
    des: "Bohemian-inspired invitation with dreamcatcher illustrations",
    path: "https://i.ibb.co/10ZbNQ2/card87.png",
    path2: "",
    path3: "",
  },
  {
    id: "card84",
    title: "Enchanted Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Chic marble design with rose gold foil accents.",
    path: "https://i.ibb.co/Np1RSLv/card88.png",
    path2: "",
    path3: "",
  },
  {
    id: "card85",
    title: "Pure Hearts",
    cat: "Hindu",
    price: 50,
    des: "Rustic woodgrain card with lace and twine details.",
    path: "https://i.ibb.co/t4mkbbm/card89.png",
    path2: "",
    path3: "",
  },
  {
    id: "card86",
    title: "Lovely Promise",
    cat: "Hindu",
    price: 50,
    des: "Modern geometric design with gold foil and bold fonts.",
    path: "https://i.ibb.co/LZCM67p/card90.png",
    path2: "",
    path3: "",
  },
  {
    id: "card87",
    title: "Joyful Vows",
    cat: "Hindu",
    price: 50,
    des: "Floral laser-cut invitation with a blush pink ribbon.",
    path: "https://i.ibb.co/hdTSJ5P/card91.png",
    path2: "",
    path3: "",
  },
  {
    id: "card88",
    title: "Radiant Love",
    cat: "Hindu",
    price: 50,
    des: "Elegant damask pattern card with silver foil accents.",
    path: "https://i.ibb.co/zbJ9xsX/card92.png",
    path2: "",
    path3: "",
  },
  {
    id: "card89",
    title: "Sweet Together",
    cat: "Hindu",
    price: 50,
    des: "Whimsical garden-themed invitation with colorful illustrations.",
    path: "https://i.ibb.co/gTxDHKJ/card93.png",
    path2: "",
    path3: "",
  },
  {
    id: "card90",
    title: "Graceful Union",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated navy and gold card with a monogrammed seal.",
    path: "https://i.ibb.co/smsPsMP/card94.png",
    path2: "",
    path3: "",
  },
  {
    id: "card91",
    title: "Dreamy Love",
    cat: "Hindu",
    price: 50,
    des: "Botanical-themed invitation with lush greenery illustrations.",
    path: "https://i.ibb.co/0fpLn6H/card95.png",
    path2: "",
    path3: "",
  },
  {
    id: "card92",
    title: "Charming Hearts",
    cat: "Hindu",
    price: 50,
    des: "Vintage-inspired card with delicate floral patterns.",
    path: "https://i.ibb.co/jhpZ3qw/card96.png",
    path2: "",
    path3: "",
  },
  {
    id: "card93",
    title: "Elegant Bliss",
    cat: "Hindu",
    price: 50,
    des: "Elegant pearl-finished invitation with embossed details.",
    path: "https://i.ibb.co/X2rCzNm/card97.png",
    path2: "",
    path3: "",
  },
  {
    id: "card94",
    title: "Pure Promise",
    cat: "Hindu",
    price: 50,
    des: "Nautical-themed card with stripes and rope accents.",
    path: "https://i.ibb.co/zb9FQKv/card98.png",
    path2: "",
    path3: "",
  },
  {
    id: "card95",
    title: "Joyous Together",
    cat: "Hindu",
    price: 50,
    des: "Floral watercolor invitation with a soft, romantic design.",
    path: "https://i.ibb.co/R6GXssj/card99.png",
    path2: "",
    path3: "",
  },
  {
    id: "card96",
    title: "Heartfelt Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Luxurious velvet card with gold foil and a satin ribbon.",
    path: "https://i.ibb.co/HBBS2wZ/card100.png",
    path2: "",
    path3: "",
  },
  {
    id: "card97",
    title: "Sacred Moments",
    cat: "Hindu",
    price: 50,
    des: "Rustic kraft paper invitation with hand-drawn botanical prints.",
    path: "https://i.ibb.co/F7zwbV9/card102.png",
    path2: "",
    path3: "",
  },
  {
    id: "card98",
    title: "Lovely Hearts",
    cat: "Hindu",
    price: 50,
    des: "Modern acrylic card with sleek, minimalist typography.",
    path: "https://i.ibb.co/KDgCgqK/card101.png",
    path2: "",
    path3: "",
  },
  {
    id: "card99",
    title: " Blissful Vows",
    cat: "Hindu",
    price: 50,
    des: "Whimsical balloon-themed invitation with colorful, playful designs.",
    path: "https://i.ibb.co/JQh9Jnr/card103.png",
    path2: "",
    path3: "",
  },
  {
    id: "card100",
    title: "Radiant Moments",
    cat: "Hindu",
    price: 50,
    des: "Vintage-inspired card with sepia tones and delicate lace",
    path: "https://i.ibb.co/fHLpPp1/card104.png",
    path2: "",
    path3: "",
  },
  {
    id: "card101",
    title: "Enchanted Union",
    cat: "Hindu",
    price: 50,
    des: "Chic black and gold invitation with art deco patterns.",
    path: "https://i.ibb.co/VN3y4vr/card105.png",
    path2: "",
    path3: "",
  },
  {
    id: "card102",
    title: "Sweet Vows",
    cat: "Hindu",
    price: 50,
    des: "Rustic woodgrain invitation with hand-painted flowers.",
    path: "https://i.ibb.co/g3qhqWN/card106.png",
    path2: "",
    path3: "",
  },
  {
    id: "card103",
    title: "Joyful Together",
    cat: "Hindu",
    price: 50,
    des: "Elegant pearl-finished card with silver embossing.",
    path: "https://i.ibb.co/5B1xkTJ/card107.png",
    path2: "",
    path3: "",
  },
  {
    id: "card104",
    title: "Serene Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Modern geometric design with monochrome palette.",
    path: "https://i.ibb.co/D7D94C1/card108.png",
    path2: "",
    path3: "",
  },
  {
    id: "card105",
    title: "Graceful Hearts",
    cat: "Hindu",
    price: 50,
    des: "Whimsical garden-themed invitation with fairy illustrations",
    path: "https://i.ibb.co/Cz59m2y/card109.png",
    path2: "",
    path3: "",
  },
  {
    id: "card106",
    title: "Dreamy Together",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated navy and gold card with classic script",
    path: "https://i.ibb.co/ssphVbk/card110.png",
    path2: "",
    path3: "",
  },
  {
    id: "card107",
    title: "Charming Moments",
    cat: "Hindu",
    price: 50,
    des: "Floral watercolor invitation with delicate lavender blooms",
    path: "https://i.ibb.co/DbbBtt0/card112.png",
    path2: "",
    path3: "",
  },
  {
    id: "card108",
    title: "Lovely Bliss",
    cat: "Hindu",
    price: 50,
    des: "Vintage postcard-style card with travel-themed illustrations",
    path: "https://i.ibb.co/F63bkMr/card113.png",
    path2: "",
    path3: "",
  },
  {
    id: "card109",
    title: "Heartfelt Promise",
    cat: "Hindu",
    price: 50,
    des: "Elegant damask pattern invitation with gold foil.",
    path: "https://i.ibb.co/HpNDK5T/card114.png",
    path2: "",
    path3: "",
  },
  {
    id: "card110",
    title: " Elegant Love",
    cat: "Hindu",
    price: 50,
    des: "Rustic kraft paper card with hand-drawn trees and twine",
    path: "https://i.ibb.co/s2z8HzD/card115.png",
    path2: "",
    path3: "",
  },
  {
    id: "card111",
    title: "True Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Glamorous glitter invitation with rose gold foil.",
    path: "https://i.ibb.co/5Fnq05F/card116.png",
    path2: "",
    path3: "",
  },
  {
    id: "card112",
    title: "Radiant Hearts",
    cat: "Hindu",
    price: 50,
    des: "Minimalist white card with clean, elegant typography.",
    path: "https://i.ibb.co/v1YxqhD/card117.png",
    path2: "",
    path3: "",
  },
  {
    id: "card113",
    title: ". Pure Moments",
    cat: "Hindu",
    price: 50,
    des: "Bohemian-style invitation with feather and floral motifs",
    path: "https://i.ibb.co/H2R3JjK/card118.png",
    path2: "",
    path3: "",
  },
  {
    id: "card114",
    title: "Joyous Vows",
    cat: "Hindu",
    price: 50,
    des: "Chic marble design with sleek black accents.",
    path: "https://i.ibb.co/brLff7S/card119.png",
    path2: "",
    path3: "",
  },
  {
    id: "card115",
    title: "Sacred Together",
    cat: "Hindu",
    price: 50,
    des: "Nautical-themed card with lighthouse and sea motifs.",
    path: "https://i.ibb.co/3MvHrZK/card120.png",
    path2: "",
    path3: "",
  },
  {
    id: "card116",
    title: "Blissful Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Floral watercolor invitation with bright peonies",
    path: "https://i.ibb.co/x1PcqSb/card121.png",
    path2: "",
    path3: "",
  },
  {
    id: "card117",
    title: "Enchanted Vows",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated black and silver card with intricate patterns.",
    path: "https://i.ibb.co/nrvhpzt/card122.png",
    path2: "",
    path3: "",
  },
  {
    id: "card118",
    title: "Sweet Hearts",
    cat: "Hindu",
    price: 50,
    des: "Rustic burlap invitation with hand-drawn wreath",
    path: "https://i.ibb.co/DWbBmpT/card123.png",
    path2: "",
    path3: "",
  },
  {
    id: "card119",
    title: "Lovely Union",
    cat: "Hindu",
    price: 50,
    des: "Modern acrylic card with bold, minimalist design",
    path: "https://i.ibb.co/R049kmZ/card124.png",
    path2: "",
    path3: "",
  },

  {
    id: "card120",
    title: "Enchanted Forest",
    cat: "Hindu",
    price: 50,
    des: "Elegant card with fairy-tale illustrations and gold foil accents.",
    path: "https://i.ibb.co/hcMpnXc/card125.png",
    path2: "",
    path3: "",
  },

  {
    id: "card121",
    title: "Celestial Night",
    cat: "Hindu",
    price: 50,
    des: "Midnight blue card with starry sky patterns and silver embossing.",
    path: "https://i.ibb.co/JpNjxcX/card126.png",
    path2: "",
    path3: "",
  },

  {
    id: "card122",
    title: "Eternal Elegance",
    cat: "Hindu",
    price: 50,
    des: "Classic white card with lace details and a satin ribbon",
    path: "https://i.ibb.co/wNsB22R/card127.png",
    path2: "",
    path3: "",
  },

  {
    id: "card123",
    title: "Golden Glamour",
    cat: "Hindu",
    price: 50,
    des: "Luxurious card with glittery gold and bold typography.",
    path: "https://i.ibb.co/hcgDz1p/card128.png",
    path2: "",
    path3: "",
  },

  {
    id: "card124",
    title: "Rustic Romance",
    cat: "Hindu",
    price: 50,
    des: " Kraft paper invitation with hand-drawn hearts and twine.",
    path: "https://i.ibb.co/F0xBcLS/card129.png",
    path2: "",
    path3: "",
  },

  {
    id: "card125",
    title: "Modern Chic",
    cat: "Hindu",
    price: 50,
    des: "Sleek monochrome card with minimalist typography.",
    path: "https://i.ibb.co/zfqSLsd/card130.png",
    path2: "",
    path3: "",
  },

  {
    id: "card126",
    title:
      "Boho BlissBohemian-style card with dreamcatcher illustrations and earthy tones.",
    cat: "Hindu",
    price: 50,
    des: "",
    path: "https://i.ibb.co/sW3gPdj/card131.png",
    path2: "",
    path3: "",
  },

  {
    id: "card127",
    title: "Vintage Charm",
    cat: "Hindu",
    price: 50,
    des: "Nostalgic postcard-style invitation with sepia floral patterns.",
    path: "https://i.ibb.co/4jbhNZv/card132.png",
    path2: "",
    path3: "",
  },

  {
    id: "card128",
    title: "Botanical Beauty",
    cat: "Hindu",
    price: 50,
    des: " Lush greenery illustrations on a sophisticated cream card.",
    path: "https://i.ibb.co/p3TnYGw/crad111.png",
    path2: "",
    path3: "",
  },
];