export const LOGO_IMG = "https://i.ibb.co/LnRSdjt/logo.png";
export const HOME_IMG = "https://i.ibb.co/s5ZNqK6/final.jpg";
export const REG_IMG = "https://i.ibb.co/RDqP0rh/backg.png";
export const LOGIN_IMG = "https://i.ibb.co/0jHj2q9/back2.png";
export const QRDetails = [
  {
    id: 1001,
    title: "Design 1",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/PmmPjWP/qr1.png",
  },
  {
    id: 1002,
    title: "Design 2",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/60jtXyL/qr2.png",
  },
  {
    id: 1003,
    title: "Design 3",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/L1cFBsf/qr3.png",
  },
  {
    id: 1004,
    title: "Design 4",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/3CTBCVL/qr4.png",
  },
  {
    id: 1005,
    title: "Design 5",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/9qNfb0d/qr5.jpg",
  },
  {
    id: 1006,
    title: "Design 6",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/RcGydjW/qr6.jpg",
  },
  {
    id: 1007,
    title: "Design 7",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/6FTHmXJ/qr7.jpg",
  },
  {
    id: 1008,
    title: "Design 8",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/7gLNTHN/qr10.jpg",
  },
  {
    id: 1009,
    title: "Design 9",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/kS6vkq4/qr27.jpg",
  },
  {
    id: 10010,
    title: "Design 10",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/7gLNTHN/qr10.jpg",
  },
  {
    id: 10011,
    title: "Design 11",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/yggm4v8/qr26.jpg",
  },
  {
    id: 10012,
    title: "Design 12",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/VL7gXbD/qr25.jpg",
  },
  {
    id: 10013,
    title: "Design 13",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/X2Yb0Gx/qr24.jpg",
  },
  {
    id: 10014,
    title: "Design 14",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/2NcmysX/qr23.jpg",
  },
  {
    id: 10015,
    title: "Design 15",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/C6jz482/qr22.png",
  },
  {
    id: 10016,
    title: "Design 16",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/qWxcYXL/qr21.png",
  },
  {
    id: 10017,
    title: "Design 17",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/MSb8NBM/qr20.png",
  },
  {
    id: 10018,
    title: "Design 18",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/jbs9MXH/qr19.png",
  },
  {
    id: 10019,
    title: "Design 19",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/hsnt3GB/qr18.jpg",
  },
  {
    id: 10020,
    title: "Design 20",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/f4DrCZp/qr14.png",
  },
  {
    id: 10021,
    title: "Design 21",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/R6x6zBc/qr13.png",
  },
  {
    id: 10022,
    title: "Design 22",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/6mDDzHK/qr12.png",
  },
  {
    id: 10023,
    title: "Design 23",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/ZByMX9h/qr11.jpg",
  },
  {
    id: 10024,
    title: "Design 24",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/PMGrK09/qr17.jpg",
  },
];
export const serviceDetails = [
  {
    id: 2000,
    path: "https://i.imghippo.com/files/2861O1725218566.png",
  },
  {
    id: 2001,
    path: "https://i.imghippo.com/files/7gwI61725218620.png",
  },
  {
    id: 2002,
    path: "https://i.imghippo.com/files/sKCMd1725218682.png",
  },
  {
    id: 2003,
    path: "https://i.imghippo.com/files/i1XQL1725218783.png",
  },
  {
    id: 2004,
    path: "https://i.imghippo.com/files/odA5v1725218786.png",
  },
  {
    id: 2005,
    path: "https://i.imghippo.com/files/EKlVs1725218821.png",
  },
  {
    id: 2006,
    path: "https://i.imghippo.com/files/0DaAF1725218841.png",
  },
];

export const videoThumbnailDetails = [
  {
    id: 1000,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Video/VIDEO1.png",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 1001,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Video/VIDEO2.png",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 1002,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Video/VIDEO3.png",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 1003,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Video/VIDEO4.png",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 1004,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Video/VIDEO5.png",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 1005,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Video/VIDEO6.png",
    des: "This card is for this this this",
    cat: "Nature",
  },
];

export const cardDetails = [

  {
    id: "card4",
    title: "Timeless Love",
    cat: "Hindu",
    price: 13,
    des: "Vintage-inspired card with delicate watercolor florals and cursive script.",
    path: "https://i.ibb.co/vVBSW0k/card5-2.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card5",
    title: "Blissful Beginnings",
    cat: "Hindu",
    price: 46,
    des: "Chic black and white invitation with bold typography and geometric shapes.",
    path: "https://i.ibb.co/RBbfwLz/card5.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card6",
    title: "Pure Romance",
    cat: "Hindu",
    price: 14,
    des: "Classic navy and gold invitation with a timeless monogram.",
    path: "https://i.ibb.co/By8wF1J/card6.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card7",
    title: "Eternal Bliss",
    cat: "Hindu",
    price: 19,
    des: "Whimsical card featuring watercolor illustrations and playful fonts.",
    path: "https://i.ibb.co/4pBdt7r/card7.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card8",
    title: "Serene Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Luxurious card with velvet touch finish and gold embossing.",
    path: "https://i.ibb.co/nCvLf7z/card9.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card9",
    title: "Classic Love",
    cat: "Hindu",
    price: 50,
    des: "Romantic blush pink invitation with rose gold foil details.",
    path: "https://i.ibb.co/khWKkP2/card10.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card10",
    title: "Heartfelt Union",
    cat: "Hindu",
    price: 50,
    des: "Tropical-themed card with vibrant palm leaves and exotic flowers",
    path: "https://i.ibb.co/tK0TvKC/card11.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card11",
    title: "Divine Love",
    cat: "Hindu",
    price: 50,
    des: "Elegant emerald green invitation with gold accents and a satin ribbon.",
    path: "https://i.ibb.co/crTmJtY/card12.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card12",
    title: "Graceful Union",
    cat: "Hindu",
    price: 50,
    des: "Art deco-inspired design with metallic accents and bold patterns.",
    path: "https://i.ibb.co/crstXWq/card13.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card13",
    title: "True Love",
    cat: "Hindu",
    price: 50,
    des: "Simple kraft paper card with twine and a wax seal",
    path: "https://i.ibb.co/j4mBZzb/card14.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card14",
    title: "Regal Wedding",
    cat: "Hindu",
    price: 50,
    des: "Nautical-themed invitation with navy stripes and anchor motifs.",
    path: "https://i.ibb.co/w6bJYth/card15.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card15",
    title: "Happy Hearts",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated marble design with gold foil details.",
    path: "https://i.ibb.co/fXz3cwt/card16.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card16",
    title: "Sweet Vows",
    cat: "Hindu",
    price: 50,
    des: "Bohemian-style card with dreamcatcher illustrations and earthy tones.",
    path: "https://i.ibb.co/Fgbrq4x/card16-2.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card17",
    title: " Beautiful Beginnings",
    cat: "Hindu",
    price: 50,
    des: "Glamorous glittery gold invitation with a classic script font.",
    path: "https://i.ibb.co/SmHVPXV/card17.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card18",
    title: "Cherished Moments",
    cat: "Hindu",
    price: 50,
    des: "Eco-friendly card made from recycled paper with botanical prints.",
    path: "https://i.ibb.co/5Lyc1v0/card18.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card19",
    title: "Precious Love",
    cat: "Hindu",
    price: 50,
    des: "Fairy tale-inspired design with enchanted forest illustrations.",
    path: "https://i.ibb.co/tzCcrpq/card19.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card20",
    title: "Love Knot",
    cat: "Hindu",
    price: 50,
    des: "Elegant cream and gold invitation with intricate laser-cut details.",
    path: "https://i.ibb.co/cDNLWgr/card20.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card21",
    title: "Serene Vows",
    cat: "Hindu",
    price: 50,
    des: "Floral watercolor card with a delicate border and elegant script.",
    path: "https://i.ibb.co/Vt347b5/card21.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card22",
    title: "Blissful Union",
    cat: "Hindu",
    price: 50,
    des: "Modern acrylic invitation with sleek typography.",
    path: "https://i.ibb.co/Rpp6C92/card22.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card23",
    title: "Perfect Pair",
    cat: "Hindu",
    price: 50,
    des: "Rustic wood veneer card with engraved details.",
    path: "https://i.ibb.co/WWztyDn/card24.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card24",
    title: " Simple Elegance",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated grey and silver invitation with a minimalist design.",
    path: "https://i.ibb.co/RpLmqkF/card23.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card25",
    title: " Pure Joy",
    cat: "Hindu",
    price: 50,
    des: "Tropical destination wedding invitation with vibrant hibiscus flowers.",
    path: "https://i.ibb.co/Qjp1Z7G/card25.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card26",
    title: "Golden Moments",
    cat: "Hindu",
    price: 50,
    des: "Whimsical balloon-themed card with colorful illustrations.",
    path: "https://i.ibb.co/GCkLJZd/card27.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card27",
    title: "Sacred Promise",
    cat: "Hindu",
    price: 50,
    des: "Vintage postcard-style invitation with a nostalgic feel.",
    path: "https://i.ibb.co/dgWvzqk/card26.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card28",
    title: " Lovely Bond",
    cat: "Hindu",
    price: 50,
    des: "Elegant pearl-finished card with lace patterns and satin bow.",
    path: "https://i.ibb.co/4KfPxJh/card28.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card29",
    title: "Joyous Journey",
    cat: "Hindu",
    price: 50,
    des: "Bold red and gold invitation with a traditional Asian design.",
    path: "https://i.ibb.co/9YB7wMY/card29.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card30",
    title: "Sweet Love",
    cat: "Hindu",
    price: 50,
    des: "Charming cottage-themed card with hand-painted flowers.",
    path: "https://i.ibb.co/R3fK1r3/card30.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card31",
    title: "Radiant Hearts",
    cat: "Hindu",
    price: 50,
    des: "Luxurious velvet card with gold foil stamping.",
    path: "https://i.ibb.co/fXx26Hp/card31.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card32",
    title: "Enchanted Love",
    cat: "Hindu",
    price: 50,
    des: "Minimalist kraft paper invitation with calligraphy.",
    path: "https://i.ibb.co/hBN889q/card32.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card33",
    title: "Elegant Affair",
    cat: "Hindu",
    price: 50,
    des: "Elegant scroll invitation with gold accents and a ribbon tie.",
    path: "https://i.ibb.co/c12NpWT/card33.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card34",
    title: "Love’s Embrace",
    cat: "Hindu",
    price: 50,
    des: "Rustic burlap card with lace and twine details.",
    path: "https://i.ibb.co/cx4XWpH/card34.png",
    path2: "",
    path3: "",
  },
  {
    id: "card35",
    title: " Dreamy Vows",
    cat: "Hindu",
    price: 50,
    des: "Classic black-tie invitation with sleek black and white design.",
    path: "https://i.ibb.co/rFH3wD0/card35.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card36",
    title: "Serene Union",
    cat: "Hindu",
    price: 50,
    des: "Nautical navy and white card with anchor details.",
    path: "https://i.ibb.co/GdG21MH/card36.png",
    path2: "",
    path3: "",
  },
  {
    id: "card37",
    title: "Charming Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Botanical-themed invitation with lush greenery illustrations.",
    path: "https://i.ibb.co/1K2yNJD/card37.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card38",
    title: "Elegant Love",
    cat: "Hindu",
    price: 50,
    des: "Vintage lace overlay card with pearl accents.",
    path: "https://i.ibb.co/xfNHGXS/card38.png",
    path2: "",
    path3: "",
  },
  {
    id: "card39",
    title: "Heartfelt Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Modern geometric design with gold foil and bold typography.",
    path: "https://i.ibb.co/ryPgfJt/card39.png",
    path2: "",
    path3: "",
  },
  {
    id: "card40",
    title: " Regal Union",
    cat: "Hindu",
    price: 50,
    des: "Floral laser-cut invitation with a blush pink ribbon.",
    path: "https://i.ibb.co/tpGJJz1/card40.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card41",
    title: "Sacred Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Elegant damask pattern card with silver foil.",
    path: "https://i.ibb.co/FgN06HL/card43.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card42",
    title: "Joyful Hearts",
    cat: "Hindu",
    price: 50,
    des: "Whimsical garden-themed card with colorful floral illustrations.",
    path: "https://i.ibb.co/5KGdp2F/card41.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card43",
    title: "Blissful Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated navy and gold invitation with a monogrammed seal.",
    path: "https://i.ibb.co/7RwqTSB/card42.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card44",
    title: "Lovely Vows",
    cat: "Hindu",
    price: 50,
    des: "Rustic kraft paper card with botanical prints and twine.",
    path: "https://i.ibb.co/bF8Jb8r/card45.png",
    path2: "",
    path3: "",
  },
  {
    id: "card45",
    title: " Pure Bliss",
    cat: "Hindu",
    price: 50,
    des: "Glamorous glitter invitation with elegant script font.",
    path: "https://i.ibb.co/T8X2c4w/card46.png",
    path2: "",
    path3: "",
  },
  {
    id: "card1",
    title: "Elegant Vows",
    cat: "Hindu",
    price: 20,
    des: "Elegant ivory card with gold foil lettering and intricate lace patterns.",
    path: "https://i.ibb.co/NFhN5J1/card1.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card2",
    title: "Joyful Union",
    cat: "Hindu",
    price: 15,
    des: "Rustic kraft paper invitation with hand-drawn floral accents.",
    path: "https://i.ibb.co/5r0HWLx/card2.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card3",
    title: "Sacred Bond",
    cat: "Hindu",
    price: 10,
    des: "Modern minimalist design with clean lines and a monochrome color scheme.",
    path: "https://i.ibb.co/y8MjkrY/card3.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card46",
    title: "Love’s Journey",
    cat: "Hindu",
    price: 50,
    des: "Minimalist white card with gold foil lettering.",
    path: "https://i.ibb.co/T8X2c4w/card46.png",
    path2: "",
    path3: "",
  },
  {
    id: "card47",
    title: "Happy Together",
    cat: "Hindu",
    price: 50,
    des: "Bohemian-inspired design with dreamcatcher and feathers.",
    path: "https://i.ibb.co/JRrXSTM/card47.png",
    path2: "",
    path3: "",
  },
  {
    id: "card48",
    title: "Sweet Harmony",
    cat: "Hindu",
    price: 50,
    des: "Rustic woodgrain invitation with delicate lace details.",
    path: "https://i.ibb.co/6nsvb77/card48.png",
    path2: "",
    path3: "",
  },
  {
    id: "card49",
    title: "Graceful Vows",
    cat: "Hindu",
    price: 50,
    des: "Modern typography-focused design with a monochrome palette.",
    path: "https://i.ibb.co/rpkLyVk/card49.png",
    path2: "",
    path3: "",
  },
  {
    id: "card50",
    title: "Eternal Love",
    cat: "Hindu",
    price: 50,
    des: "Chic marble card with rose gold accents.",
    path: "https://i.ibb.co/XZxTsCQ/card50.png",
    path2: "",
    path3: "",
  },
  {
    id: "card51",
    title: "Pure Union",
    cat: "Hindu",
    price: 50,
    des: "Vintage-inspired card with pastel florals and cursive script.",
    path: "https://i.ibb.co/3N9Bry6/card51.png",
    path2: "",
    path3: "",
  },
  {
    id: "card52",
    title: "Joyful Moments",
    cat: "Hindu",
    price: 50,
    des: "Elegant pearl-finished invitation with embossed patterns.",
    path: "https://i.ibb.co/MncN3r1/card53.png",
    path2: "",
    path3: "",
  },
  {
    id: "card53",
    title: "Lovely Together",
    cat: "Hindu",
    price: 50,
    des: "Nautical-themed card with stripes and rope details.",
    path: "https://i.ibb.co/xMHGQpR/card55.png",
    path2: "",
    path3: "",
  },
  {
    id: "card54",
    title: "Heartfelt Vows",
    cat: "Hindu",
    price: 50,
    des: "Floral watercolor invitation with a soft, romantic feel.",
    path: "https://i.ibb.co/ySvS55L/card56.png",
    path2: "",
    path3: "",
  },
  {
    id: "card55",
    title: "Sacred Hearts",
    cat: "Hindu",
    price: 50,
    des: "Luxurious velvet card with gold foil and satin ribbon.",
    path: "https://i.ibb.co/t3GJHt0/card57.png",
    path2: "",
    path3: "",
  },
  {
    id: "card56",
    title: "Blissful Together",
    cat: "Hindu",
    price: -1,
    des: "Rustic kraft paper card with hand-drawn illustrations.",
    path: "https://i.ibb.co/b15yjHm/card58.png",
    path2: "",
    path3: "",
  },
  {
    id: "card57",
    title: "Elegant Union",
    cat: "Hindu",
    price: 50,
    des: "Modern acrylic invitation with sleek, transparent design.",
    path: "https://i.ibb.co/K5JJbsp/card59.png",
    path2: "",
    path3: "",
  },
  {
    id: "card58",
    title: "True Joy",
    cat: "Hindu",
    price: 50,
    des: "Botanical-themed card with lush greenery and elegant script.",
    path: "https://i.ibb.co/VSL0hv7/card60.png",
    path2: "",
    path3: "",
  },
  {
    id: "card59",
    title: "Radiant Union",
    cat: "Hindu",
    price: 50,
    des: "Chic black and gold invitation with a sophisticated feel.",
    path: "https://i.ibb.co/s2MQKNc/card61.png",
    path2: "",
    path3: "",
  },
  {
    id: "card60",
    title: " Enchanted Hearts",
    cat: "Hindu",
    price: 50,
    des: "Whimsical garden party-themed card with colorful illustrations.",
    path: "https://i.ibb.co/t3N28hr/card62.png",
    path2: "",
    path3: "",
  },
  {
    id: "card61",
    title: "Charming Love",
    cat: "Hindu",
    price: 50,
    des: "Classic cream and gold invitation with a timeless design.",
    path: "https://i.ibb.co/Kyp6R7R/card63.png",
    path2: "",
    path3: "",
  },
  {
    id: "card62",
    title: "Lovely Moments",
    cat: "Hindu",
    price: 50,
    des: "Vintage lace overlay card with delicate details.",
    path: "https://i.ibb.co/7XNPwrd/card64.png",
    path2: "",
    path3: "",
  },
  {
    id: "card63",
    title: "Joyous Union",
    cat: "Hindu",
    price: 50,
    des: "Minimalist kraft paper invitation with simple typography.",
    path: "https://i.ibb.co/JpF5T2r/card65.png",
    path2: "",
    path3: "",
  },
  {
    id: "card64",
    title: " Pure Vows",
    cat: "Hindu",
    price: 50,
    des: "Elegant damask pattern card with silver foil accents.",
    path: "https://i.ibb.co/3dF23bY/card66.png",
    path2: "",
    path3: "",
  },
  {
    id: "card65",
    title: "Sweet Moments",
    cat: "Hindu",
    price: 50,
    des: "Rustic burlap and lace invitation with twine bow.",
    path: "https://i.ibb.co/tJxt89f/card67.png",
    path2: "",
    path3: "",
  },
  {
    id: "card66",
    title: "Heartfelt Love",
    cat: "Hindu",
    price: 50,
    des: "Glamorous glitter invitation with bold gold accents.",
    path: "https://i.ibb.co/4PD9Ynv/card68.png",
    path2: "",
    path3: "",
  },
  {
    id: "card129",
    title: " Sacred Bliss",
    cat: "Hindu",
    price: 50,
    des: "Modern monochrome design with clean lines and sleek typography.",
    path: "https://i.ibb.co/5v9SJnv/card69.png",
    path2: "",
    path3: "",
  },
  {
    id: "card67",
    title: "Elegant Together",
    cat: "Hindu",
    price: 50,
    des: "Floral watercolor card with soft, pastel hues.",
    path: "https://i.ibb.co/Gd3sx71/card70.png",
    path2: "",
    path3: "",
  },
  {
    id: "card68",
    title: " Joyful Promise",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated navy and silver invitation with a monogram.",
    path: "https://i.ibb.co/YtPb89T/card71.png",
    path2: "",
    path3: "",
  },
  {
    id: "card69",
    title: "Dreamy Hearts",
    cat: "Hindu",
    price: 50,
    des: "Botanical-themed card with hand-drawn illustrations and earthy tones.",
    path: "https://i.ibb.co/Ws11mVm/card72.png",
    path2: "",
    path3: "",
  },
  {
    id: "card70",
    title: ". Love’s Harmony",
    cat: "Hindu",
    price: 50,
    des: "Vintage-inspired postcard invitation with a nostalgic design.",
    path: "https://i.ibb.co/DwFfhYg/card73.png",
    path2: "",
    path3: "",
  },
  {
    id: "card71",
    title: " Graceful Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Chic marble card with gold foil and elegant script.",
    path: "https://i.ibb.co/kgjjHmr/card75.png",
    path2: "",
    path3: "",
  },
  {
    id: "card72",
    title: "Pure Together",
    cat: "Hindu",
    price: 50,
    des: "Rustic wood veneer invitation with engraved details.",
    path: "https://i.ibb.co/6wnsRzD/card76.png",
    path2: "",
    path3: "",
  },
  {
    id: "card73",
    title: "Happy Vows",
    cat: "Hindu",
    price: 50,
    des: "Modern acrylic card with a minimalist design",
    path: "https://i.ibb.co/5cJJTfg/card77.png",
    path2: "",
    path3: "",
  },
  {
    id: "card74",
    title: ". Radiant Bliss",
    cat: "Hindu",
    price: 50,
    des: "Whimsical balloon-themed invitation with playful illustrations.",
    path: "https://i.ibb.co/Pzmt5T9/card78.png",
    path2: "",
    path3: "",
  },
  {
    id: "card75",
    title: "Serene Hearts",
    cat: "Hindu",
    price: 50,
    des: "Elegant pearl-finished card with intricate lace patterns.",
    path: "https://i.ibb.co/w7b4ndh/card79.png",
    path2: "",
    path3: "",
  },
  {
    id: "card76",
    title: "Charming Vows",
    cat: "Hindu",
    price: 50,
    des: "Nautical-themed invitation with navy stripes and anchor motifs.",
    path: "https://i.ibb.co/P4SsVjk/card80.png",
    path2: "",
    path3: "",
  },
  {
    id: "card77",
    title: "Lovely Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Floral watercolor card with a delicate border and cursive script.",
    path: "https://i.ibb.co/fphHPKm/card81.png",
    path2: "",
    path3: "",
  },
  {
    id: "card78",
    title: "Joyous Promise",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated black and white design with bold typography.",
    path: "https://i.ibb.co/Thqj7nF/card82.png",
    path2: "",
    path3: "",
  },
  {
    id: "card79",
    title: "Heartfelt Union",
    cat: "Hindu",
    price: 50,
    des: "Vintage lace overlay card with pearl accents.",
    path: "https://i.ibb.co/kQdHgnG/card83.png",
    path2: "",
    path3: "",
  },
  {
    id: "card80",
    title: "Blissful Love",
    cat: "Hindu",
    price: 50,
    des: "Rustic kraft paper invitation with botanical prints and twine.",
    path: "https://i.ibb.co/hHp9Qtm/card84.png",
    path2: "",
    path3: "",
  },
  {
    id: "card81",
    title: "Elegant Moments",
    cat: "Hindu",
    price: 50,
    des: "Glamorous glitter invitation with elegant gold foil.",
    path: "https://i.ibb.co/74Kt4bN/card85.png",
    path2: "",
    path3: "",
  },
  {
    id: "card82",
    title: "True Together",
    cat: "Hindu",
    price: 50,
    des: "Minimalist white card with sleek, modern typography",
    path: "https://i.ibb.co/hZF9psH/card86.png",
    path2: "",
    path3: "",
  },
  {
    id: "card83",
    title: "Sacred Joy",
    cat: "Hindu",
    price: 50,
    des: "Bohemian-inspired invitation with dreamcatcher illustrations",
    path: "https://i.ibb.co/10ZbNQ2/card87.png",
    path2: "",
    path3: "",
  },
  {
    id: "card84",
    title: "Enchanted Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Chic marble design with rose gold foil accents.",
    path: "https://i.ibb.co/Np1RSLv/card88.png",
    path2: "",
    path3: "",
  },
  {
    id: "card85",
    title: "Pure Hearts",
    cat: "Hindu",
    price: 50,
    des: "Rustic woodgrain card with lace and twine details.",
    path: "https://i.ibb.co/t4mkbbm/card89.png",
    path2: "",
    path3: "",
  },
  {
    id: "card86",
    title: "Lovely Promise",
    cat: "Hindu",
    price: 50,
    des: "Modern geometric design with gold foil and bold fonts.",
    path: "https://i.ibb.co/LZCM67p/card90.png",
    path2: "",
    path3: "",
  },
  {
    id: "card87",
    title: "Joyful Vows",
    cat: "Hindu",
    price: 50,
    des: "Floral laser-cut invitation with a blush pink ribbon.",
    path: "https://i.ibb.co/hdTSJ5P/card91.png",
    path2: "",
    path3: "",
  },
  {
    id: "card88",
    title: "Radiant Love",
    cat: "Hindu",
    price: 50,
    des: "Elegant damask pattern card with silver foil accents.",
    path: "https://i.ibb.co/zbJ9xsX/card92.png",
    path2: "",
    path3: "",
  },
  {
    id: "card89",
    title: "Sweet Together",
    cat: "Hindu",
    price: 50,
    des: "Whimsical garden-themed invitation with colorful illustrations.",
    path: "https://i.ibb.co/gTxDHKJ/card93.png",
    path2: "",
    path3: "",
  },
  {
    id: "card90",
    title: "Graceful Union",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated navy and gold card with a monogrammed seal.",
    path: "https://i.ibb.co/smsPsMP/card94.png",
    path2: "",
    path3: "",
  },
  {
    id: "card91",
    title: "Dreamy Love",
    cat: "Hindu",
    price: 50,
    des: "Botanical-themed invitation with lush greenery illustrations.",
    path: "https://i.ibb.co/0fpLn6H/card95.png",
    path2: "",
    path3: "",
  },
  {
    id: "card92",
    title: "Charming Hearts",
    cat: "Hindu",
    price: 50,
    des: "Vintage-inspired card with delicate floral patterns.",
    path: "https://i.ibb.co/jhpZ3qw/card96.png",
    path2: "",
    path3: "",
  },
  {
    id: "card93",
    title: "Elegant Bliss",
    cat: "Hindu",
    price: 50,
    des: "Elegant pearl-finished invitation with embossed details.",
    path: "https://i.ibb.co/X2rCzNm/card97.png",
    path2: "",
    path3: "",
  },
  {
    id: "card94",
    title: "Pure Promise",
    cat: "Hindu",
    price: 50,
    des: "Nautical-themed card with stripes and rope accents.",
    path: "https://i.ibb.co/zb9FQKv/card98.png",
    path2: "",
    path3: "",
  },
  {
    id: "card95",
    title: "Joyous Together",
    cat: "Hindu",
    price: 50,
    des: "Floral watercolor invitation with a soft, romantic design.",
    path: "https://i.ibb.co/R6GXssj/card99.png",
    path2: "",
    path3: "",
  },
  {
    id: "card96",
    title: "Heartfelt Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Luxurious velvet card with gold foil and a satin ribbon.",
    path: "https://i.ibb.co/HBBS2wZ/card100.png",
    path2: "",
    path3: "",
  },
  {
    id: "card97",
    title: "Sacred Moments",
    cat: "Hindu",
    price: 50,
    des: "Rustic kraft paper invitation with hand-drawn botanical prints.",
    path: "https://i.ibb.co/F7zwbV9/card102.png",
    path2: "",
    path3: "",
  },
  {
    id: "card98",
    title: "Lovely Hearts",
    cat: "Hindu",
    price: 50,
    des: "Modern acrylic card with sleek, minimalist typography.",
    path: "https://i.ibb.co/KDgCgqK/card101.png",
    path2: "",
    path3: "",
  },
  {
    id: "card99",
    title: " Blissful Vows",
    cat: "Hindu",
    price: 50,
    des: "Whimsical balloon-themed invitation with colorful, playful designs.",
    path: "https://i.ibb.co/JQh9Jnr/card103.png",
    path2: "",
    path3: "",
  },
  {
    id: "card100",
    title: "Radiant Moments",
    cat: "Hindu",
    price: 50,
    des: "Vintage-inspired card with sepia tones and delicate lace",
    path: "https://i.ibb.co/fHLpPp1/card104.png",
    path2: "",
    path3: "",
  },
  {
    id: "card101",
    title: "Enchanted Union",
    cat: "Hindu",
    price: 50,
    des: "Chic black and gold invitation with art deco patterns.",
    path: "https://i.ibb.co/VN3y4vr/card105.png",
    path2: "",
    path3: "",
  },
  {
    id: "card102",
    title: "Sweet Vows",
    cat: "Hindu",
    price: 50,
    des: "Rustic woodgrain invitation with hand-painted flowers.",
    path: "https://i.ibb.co/g3qhqWN/card106.png",
    path2: "",
    path3: "",
  },
  {
    id: "card103",
    title: "Joyful Together",
    cat: "Hindu",
    price: 50,
    des: "Elegant pearl-finished card with silver embossing.",
    path: "https://i.ibb.co/5B1xkTJ/card107.png",
    path2: "",
    path3: "",
  },
  {
    id: "card104",
    title: "Serene Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Modern geometric design with monochrome palette.",
    path: "https://i.ibb.co/D7D94C1/card108.png",
    path2: "",
    path3: "",
  },
  {
    id: "card105",
    title: "Graceful Hearts",
    cat: "Hindu",
    price: 50,
    des: "Whimsical garden-themed invitation with fairy illustrations",
    path: "https://i.ibb.co/Cz59m2y/card109.png",
    path2: "",
    path3: "",
  },
  {
    id: "card106",
    title: "Dreamy Together",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated navy and gold card with classic script",
    path: "https://i.ibb.co/ssphVbk/card110.png",
    path2: "",
    path3: "",
  },
  {
    id: "card107",
    title: "Charming Moments",
    cat: "Hindu",
    price: 50,
    des: "Floral watercolor invitation with delicate lavender blooms",
    path: "https://i.ibb.co/DbbBtt0/card112.png",
    path2: "",
    path3: "",
  },
  {
    id: "card108",
    title: "Lovely Bliss",
    cat: "Hindu",
    price: 50,
    des: "Vintage postcard-style card with travel-themed illustrations",
    path: "https://i.ibb.co/F63bkMr/card113.png",
    path2: "",
    path3: "",
  },
  {
    id: "card109",
    title: "Heartfelt Promise",
    cat: "Hindu",
    price: 50,
    des: "Elegant damask pattern invitation with gold foil.",
    path: "https://i.ibb.co/HpNDK5T/card114.png",
    path2: "",
    path3: "",
  },
  {
    id: "card110",
    title: " Elegant Love",
    cat: "Hindu",
    price: 50,
    des: "Rustic kraft paper card with hand-drawn trees and twine",
    path: "https://i.ibb.co/s2z8HzD/card115.png",
    path2: "",
    path3: "",
  },
  {
    id: "card111",
    title: "True Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Glamorous glitter invitation with rose gold foil.",
    path: "https://i.ibb.co/5Fnq05F/card116.png",
    path2: "",
    path3: "",
  },
  {
    id: "card112",
    title: "Radiant Hearts",
    cat: "Hindu",
    price: 50,
    des: "Minimalist white card with clean, elegant typography.",
    path: "https://i.ibb.co/v1YxqhD/card117.png",
    path2: "",
    path3: "",
  },
  {
    id: "card113",
    title: ". Pure Moments",
    cat: "Hindu",
    price: 50,
    des: "Bohemian-style invitation with feather and floral motifs",
    path: "https://i.ibb.co/H2R3JjK/card118.png",
    path2: "",
    path3: "",
  },
  {
    id: "card114",
    title: "Joyous Vows",
    cat: "Hindu",
    price: 50,
    des: "Chic marble design with sleek black accents.",
    path: "https://i.ibb.co/brLff7S/card119.png",
    path2: "",
    path3: "",
  },
  {
    id: "card115",
    title: "Sacred Together",
    cat: "Hindu",
    price: 50,
    des: "Nautical-themed card with lighthouse and sea motifs.",
    path: "https://i.ibb.co/3MvHrZK/card120.png",
    path2: "",
    path3: "",
  },
  {
    id: "card116",
    title: "Blissful Ceremony",
    cat: "Hindu",
    price: 50,
    des: "Floral watercolor invitation with bright peonies",
    path: "https://i.ibb.co/x1PcqSb/card121.png",
    path2: "",
    path3: "",
  },
  {
    id: "card117",
    title: "Enchanted Vows",
    cat: "Hindu",
    price: 50,
    des: "Sophisticated black and silver card with intricate patterns.",
    path: "https://i.ibb.co/nrvhpzt/card122.png",
    path2: "",
    path3: "",
  },
  {
    id: "card118",
    title: "Sweet Hearts",
    cat: "Hindu",
    price: 50,
    des: "Rustic burlap invitation with hand-drawn wreath",
    path: "https://i.ibb.co/DWbBmpT/card123.png",
    path2: "",
    path3: "",
  },
  {
    id: "card119",
    title: "Lovely Union",
    cat: "Hindu",
    price: 50,
    des: "Modern acrylic card with bold, minimalist design",
    path: "https://i.ibb.co/R049kmZ/card124.png",
    path2: "",
    path3: "",
  },

  {
    id: "card120",
    title: "Enchanted Forest",
    cat: "Hindu",
    price: 50,
    des: "Elegant card with fairy-tale illustrations and gold foil accents.",
    path: "https://i.ibb.co/hcMpnXc/card125.png",
    path2: "",
    path3: "",
  },

  {
    id: "card121",
    title: "Celestial Night",
    cat: "Hindu",
    price: 50,
    des: "Midnight blue card with starry sky patterns and silver embossing.",
    path: "https://i.ibb.co/JpNjxcX/card126.png",
    path2: "",
    path3: "",
  },

  {
    id: "card122",
    title: "Eternal Elegance",
    cat: "Hindu",
    price: 50,
    des: "Classic white card with lace details and a satin ribbon",
    path: "https://i.ibb.co/wNsB22R/card127.png",
    path2: "",
    path3: "",
  },

  {
    id: "card123",
    title: "Golden Glamour",
    cat: "Hindu",
    price: 50,
    des: "Luxurious card with glittery gold and bold typography.",
    path: "https://i.ibb.co/hcgDz1p/card128.png",
    path2: "",
    path3: "",
  },

  {
    id: "card124",
    title: "Rustic Romance",
    cat: "Hindu",
    price: 50,
    des: " Kraft paper invitation with hand-drawn hearts and twine.",
    path: "https://i.ibb.co/F0xBcLS/card129.png",
    path2: "",
    path3: "",
  },

  {
    id: "card125",
    title: "Modern Chic",
    cat: "Hindu",
    price: 50,
    des: "Sleek monochrome card with minimalist typography.",
    path: "https://i.ibb.co/zfqSLsd/card130.png",
    path2: "",
    path3: "",
  },

  {
    id: "card126",
    title:
      "Boho BlissBohemian-style card with dreamcatcher illustrations and earthy tones.",
    cat: "Hindu",
    price: 50,
    des: "",
    path: "https://i.ibb.co/sW3gPdj/card131.png",
    path2: "",
    path3: "",
  },

  {
    id: "card127",
    title: "Vintage Charm",
    cat: "Hindu",
    price: 50,
    des: "Nostalgic postcard-style invitation with sepia floral patterns.",
    path: "https://i.ibb.co/4jbhNZv/card132.png",
    path2: "",
    path3: "",
  },

  {
    id: "card128",
    title: "Botanical Beauty",
    cat: "Hindu",
    price: 50,
    des: " Lush greenery illustrations on a sophisticated cream card.",
    path: "https://i.ibb.co/p3TnYGw/crad111.png",
    path2: "",
    path3: "",
  },
];

export const videoDetails = [
  {
    id: "video1",
    title: "United in Love",
    cat: "Hindu",
    price: "20",
    des: "Celebrate in Style with Our Invitation Video Collection!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/agSOz0DsJjo",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/agSOz0DsJjo?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "agSOz0DsJjo?si=wswSQ6bhvbOMwdmS",
  },

  {
    id: "video2",
    title: "The Ultimate Love Story",
    cat: "Hindu",
    price: "20",
    des: "Join Us for a Memorable Celebration – We Look Forward to Seeing You!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/lq-5O8zzzpg",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/lq-5O8zzzpg?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "lq-5O8zzzpg?si=707yi_5UIn4BtOBW",
  },

  {
    id: "video3",
    title: "A Lifetime of Love",
    cat: "Hindu",
    price: "20",
    des: "Your Presence is Requested at Our Upcoming Event!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/0y8-SnS6kzk",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/0y8-SnS6kzk?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "0y8-SnS6kzk?si=x3CEqeut4Z4P6Pkt",
  },

  {
    id: "video4",
    title: "Together in Love",
    cat: "Hindu",
    price: "20",
    des: "Come Celebrate This Special Occasion with Us!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/vCBJd5Gzyxc",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/vCBJd5Gzyxc?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "vCBJd5Gzyxc?si=ilnWLgsOUWyUMgBr",
  },

  {
    id: "video5",
    title: "Our Love Adventure",
    cat: "Hindu",
    price: "20",
    des: "We're Excited to Celebrate with You – Don't Miss Out!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/DSaYsNRb9TA",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/DSaYsNRb9TA?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "DSaYsNRb9TA?si=BtnnkyfQQjnQpfHQ",
  },

  {
    id: "video6",
    title: "The Day We Say 'I Do'",
    cat: "Hindu",
    price: "20",
    des: "A Celebration to Remember Awaits – Save the Date!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/agSOz0DsJjo",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/agSOz0DsJjo?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "agSOz0DsJjo?si=igwx4tEOg1Nj4iwr",
  },

  {
    id: "video7",
    title: "A Joyful Celebration",
    cat: "Hindu",
    price: "20",
    des: "Join Us for an Evening of Fun and Festivities!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/oiSzHzyGv1w",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/oiSzHzyGv1w?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "oiSzHzyGv1w?si=7_EoLkYjIkUB6oq-",
  },

  {
    id: "video8",
    title: "Hearts in Harmony",
    cat: "Hindu",
    price: "20",
    des: "Join Us for an Evening of Fun and Festivities!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/xPWu0a5Gmv0",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/xPWu0a5Gmv0?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "xPWu0a5Gmv0?si=MMFz0kCLLo_0AQc_",
  },

  {
    id: "video9",
    title: "The Sweetest Day",
    cat: "Hindu",
    price: "20",
    des: "Get Ready for a Special Day – We Can't Wait to Celebrate with You!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/LJJL32WyLEU",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/LJJL32WyLEU?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "LJJL32WyLEU?si=rV_4RxMbKY5qjfVo",
  },

  {
    id: "video10",
    title: "Our Fairytale Wedding",
    cat: "Hindu",
    price: "20",
    des: "Create Unforgettable First Impressions with Our Invitation Videos!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/AOPDn2zNxIs?",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/AOPDn2zNxIs?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "AOPDn2zNxIs?si=BUSY9i5NKIILz_ko",
  },

  {
    id: "video11",
    title: "An Enchanted Love",
    cat: "Hindu",
    price: "20",
    des: "Mark Your Calendar for an Event You Won't Want to Miss!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/qrDRDbkKtS0",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/qrDRDbkKtS0?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "qrDRDbkKtS0",
  },

  {
    id: "video12",
    title: "The Love Knot",
    cat: "Hindu",
    price: "20",
    des: "Captivate Your Guests with Beautiful Invitation Videos!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/Mladm2r8_5E",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/Mladm2r8_5E?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "Mladm2r8_5E",
  },

  {
    id: "video13",
    title: "The Big Celebration",
    cat: "Hindu",
    price: "20",
    des: "From Classic to Modern: Invitation Videos for Every Occasion!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/0CeZXIwNvJU?",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/0CeZXIwNvJU?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "0CeZXIwNvJU",
  },

  {
    id: "video14",
    title: "Wedding Bells",
    cat: "Hindu",
    price: "20",
    des: "Invite in Style: Explore Our Diverse Video Invitations!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/JmK1STnOEdQ",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/JmK1STnOEdQ?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "JmK1STnOEdQ",
  },

  {
    id: "video15",
    title: "The Union of Two Souls",
    cat: "Muslim",
    price: "20",
    des: "Set the Tone with Creative and Elegant Invitation Videos!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/Pg9wK671-w8",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/Pg9wK671-w8?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "Pg9wK671-w8",
  },

  {
    id: "video16",
    title: "The Perfect Union",
    cat: "Hindu",
    price: "20",
    des: "Craft the Perfect Invite with Our Stunning Video Templates!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/5qXczNx4OVg",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/5qXczNx4OVg?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "5qXczNx4OVg",
  },

  {
    id: "video17",
    title: "Hearts Entwined",
    cat: "Muslim",
    price: "20",
    des: "Transform Your Event with Unique Invitation Videos!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/pFzk7o_UdrA",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/pFzk7o_UdrA?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "pFzk7o_UdrA",
  },

  {
    id: "video18",
    title: "Love and Laughter",
    cat: "Hindu",
    price: "20",
    des: "Elevate Your Event with Personalized Invitation Videos!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/1vaL4HGPfSQ",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/1vaL4HGPfSQ?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "1vaL4HGPfSQ",
  },
];
export const video12 = [
  {
    id: "Type1",
    title: "Traditional",
    des: "Traditional photography captures timeless moments, preserving the elegance and beauty of your love story for a lifetime.",
    star: "4.9 🌟",
    rating: "(20 reviews)",
    path: "https://i.pinimg.com/736x/95/a8/5f/95a85fafee35613322e38a15bbd7731a.jpg",
    link: "/Scan"
  },
  {
    id: "Type2",
    title: "Cinematic & Candid",
    des: "Cinematic photography captures the grandeur of a moment, while candid photography reveals its unfiltered truth",
    star: "4.5 🌟",
    rating: "(18 reviews)",
    path: "https://images.travelandleisureasia.com/wp-content/uploads/sites/2/2020/11/Inside-image-Wedding-Photographers6.jpg",
    link: "/Photoinfo2"
  },
  {
    id: "Type3",
    title: "Cinematic",
    des: "Cinematic videography transforms moments into visual stories with a film-like quality and artistic flair.",
    star: "5 🌟",
    rating: "(12 reviews)",
    path: "https://5.imimg.com/data5/SELLER/Default/2020/12/NW/VN/PO/114792623/wedding-photography-500x500.jpg",
    link: "/Photoinfo3"
  },
  {
    id: "Type4",
    title: "Pre-Wedding",
    des: "Pre-wedding videography captures the joy and romance of your love story, creating memories before the big day",
    star: "4.7 🌟",
    rating: "(10 reviews)",
    path: "https://www.pixelworks.in/wp-content/uploads/2017/05/Pre-Wedding-Shoot-2.jpg",
    link: "/Photoinfo4"
  },
  {
    id: "Type5",
    title: "Classic",
    des: "Classic photography captures timeless moments with exceptional quality and affordability",
    star: "4.4 🌟",
    rating: "(15 reviews)",
    path: "https://assets.vogue.in/photos/6360ee4b74016d3adc45f105/1:1/w_4534,h_4534,c_limit/JR.WP-244.jpg",
    link: "/Photoinfo5"
  },
  {
    id: "Type6",
    title: "Cheap & best",
    des: "Premier photography captures unforgettable moments with outstanding quality and great value.",
    star: "4.2 🌟",
    rating: "(13 reviews)",
    path: "https://www.thewedcafe.com/wp-content/uploads/2020/05/09-PRD_0113-Edit.jpg",
    link: "/Photoinfo6",
  },
  {
    id: "Type7",
    title: "Trational(pre)",
    des: "Traditional premium photography preserves cherished moments with timeless quality and expert craftsmanship, delivering exceptional value.",
    star: "5 🌟",
    rating: "(30 reviews)",
    path: "https://www.weddingsutra.com/images/neelutsav.jpg",
    link: "/Photoinfo7",
  },
  {
    id: "Type8",
    title: "Standard",
    des: "Standard photography captures special moments with reliable quality and attention, offering good value.",
    star: "5 🌟",
    rating: "(23 reviews)",
    path: "https://www.shaadibaraati.com/vendors-profile/2731767e69b62b9a415e6365377d2475.jpeg",
    link: "/Photoinfo8",
  },
  {
    id: "Type9",
    title: "Premiun",
    des: "Premium photography captures memories with top quality and expert detail, offering great value.",
    star: "5 🌟",
    rating: "(25 reviews)",
    path: "https://i.pinimg.com/736x/36/e7/d3/36e7d37bdd521f8dba3f464317433b15.jpg",
    link: "/Photoinfo9",
  },
];
export const Images1 = [
  {
    id: 1,
    image: "https://i.pinimg.com/736x/74/94/d1/7494d17763649a020aa7d08967a0370d.jpg",
    po: 1,
  },
  {
    id: 2,
    image: "https://fashionatestudio.com/wp-content/uploads/2024/05/DSC_3101-scaled.jpg",
    po: 2,
  },
  {
    id: 3,
    image: "https://www.teribphotography.com/wp-content/uploads/2022/11/indian-wedding-photography-33-1202x1800.jpg",
    po: 3,
  },
  {
    id: 4,
    image: "https://vishaldhupiaphotography.com/new-images/Candid-Wedding-Photography.jpeg",
    po: 4,

  },
  {
    id: 5,
    image: "https://image.wedmegood.com/resized/800X/uploads/member/412177/1532739203_25488435_1983119855297124_6517770107131706388_o.jpg",
    po: 5,

  },
  {
    id: 6,
    image: "https://josephkingphotography.in/wp-content/uploads/2022/08/Joseph-King-Photography-Wedding-Photography-Indore-63-300x200.jpg",
    po: 6,

  },
  {
    id: 7,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLyPt_pUPRDHMpmr2c7DZBOJrbaDO1u35pjA&s",
    po: 7,

  },
  {
    id: 8,
    image: "https://live.staticflickr.com/4813/46402658441_6e44206064_b.jpg",
    po: 8,

  },
  {
    id: 9,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrvg_JajvmzCaA_3vzuk2X9yKKQ0yITeLYXg&s",
    po: 9,

  },
  {
    id: 10,
    image: "https://i.pinimg.com/736x/a8/b5/60/a8b5603e596abaeb3a7ada2b908bf45b.jpg",
    po: 10,

  },
  {
    id: 11,
    image: "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/13eb4c24745363.56339f559bf3e.jpg",
    po: 11,

  },
  {
    id: 12,
    image: "https://oneeyevisionphotography.com/wp-content/uploads/2021/08/KAT1028.jpg",
    po: 12,

  },
  {
    id: 13,
    image: "https://camrinfilms.com/photos/345605560_969198427439983_4776823517238102241_n.jpg",
    po: 13,
  },
  {
    id: 14,
    image: "https://mir-s3-cdn-cf.behance.net/project_modules/fs/1f573524745363.56339f5559a8e.jpg",
    po: 14,

  },
  {
    id: 15,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRotzMceJfmv9l2tThYFxVwgRKKee48-bjQA&s",
    po: 15,

  },
  {
    id: 16,
    image: "https://miro.medium.com/v2/resize:fit:1080/1*yaQvcdIKjFwdh3m-t2Tx6w.jpeg",
    po: 16,

  },
  {
    id: 17,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaMGHgbNHv5Ny8SUP9CZaVrINWjs46mk6pEg&s",
    po: 17,

  },
  {
    id: 18,
    image: "https://i.pinimg.com/736x/4f/c0/2e/4fc02ebabab3f7bc579e37ee51538c3e.jpg",
    po: 18,

  },
  {
    id: 19,
    image: "https://cdn0.weddingwire.in/vendor/6101/3_2/960/jpg/red-studio-wedding-cinematography-3_15_216101-157181586853596.jpeg",
    po: 19,

  },
  {
    id: 20,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbgnxJz2gphYOUarhCyTXxCFfiWcMOZnlQIg&s",
    po: 20,

  },
];

export const Images2 = [
  {
    id: 1,
    image: "https://i.ibb.co/cyB43rw/Screenshot-2024-08-21-210439.png",
    po: 1,
  },
  {
    id: 2,
    image: "https://i.ibb.co/TqhxPPR/Screenshot-2024-08-21-210430.png",
    po: 2,
  },
  {
    id: 3,
    image: "https://i.ibb.co/kcJXRC8/Screenshot-2024-08-21-210313.png",
    po: 3,
  },
  {
    id: 4,
    image: "https://i.ibb.co/dmX2Q5B/Screenshot-2024-08-21-210244.png",
    po: 4,

  },
  {
    id: 5,
    image: "https://i.ibb.co/MBWyqWL/Screenshot-2024-08-21-210236.png",
    po: 5,

  },
  {
    id: 6,
    image: "https://i.ibb.co/tMvkRrF/Screenshot-2024-08-21-210121.png",
    po: 6,

  },
  {
    id: 7,
    image: "https://i.ibb.co/HVFsGmv/Screenshot-2024-08-21-210344.png",
    po: 7,

  },
  {
    id: 8,
    image: "https://i.ibb.co/nnvX1dK/Screenshot-2024-08-21-205940.png",
    po: 8,

  },
  {
    id: 9,
    image: "https://i.ibb.co/yR2FH4g/Screenshot-2024-08-21-205922.png",
    po: 9,

  },
  {
    id: 10,
    image: "https://i.ibb.co/bP1j4V2/Screenshot-2024-08-21-205837.png",
    po: 10,

  },
  {
    id: 11,
    image: "https://i.ibb.co/nBWCbC9/4.jpg",
    po: 11,
  },
  {
    id: 12,
    image: "https://i.ibb.co/9Twmb38/2.jpg",
    po: 12,

  },
  {
    id: 13,
    image: "https://i.ibb.co/bJCVbtG/5.jpg",
    po: 13,
  },
  {
    id: 14,
    image: "https://i.ibb.co/0cQtV4m/3.jpg",
    po: 14,

  },
  {
    id: 15,
    image: "https://i.ibb.co/nBWCbC9/4.jpg",
    po: 15,
  },
  {
    id: 16,
    image: "https://i.ibb.co/HDyPXc6/6.jpg",
    po: 16,
  },
  {
    id: 17,
    image: "https://i.ibb.co/4ZXSfQp/Screenshot-2024-08-21-205327.png",
    po: 17,

  },
  {
    id: 18,
    image: "https://i.ibb.co/LQBDDnW/Screenshot-2024-08-21-205308.png",
    po: 18,

  },
  {
    id: 19,
    image: "https://i.ibb.co/K71T0jR/Screenshot-2024-08-21-210136.png",
    po: 19,

  },
  {
    id: 20,
    image: "https://i.ibb.co/YNHb4SS/1.jpg",
    po: 20,

  },
];

export const albumData = [
  {
    id: "600",
    link: "https://drive.google.com/file/d/168jwlp8FnGr032d812oFqegTy4k_RLiM/view?usp=drive_link",
    imgsrc: "https://i.ytimg.com/vi/QxPujBO-VXg/hqdefault.jpg",
  },
  {
    id: "601",
    link: "https://drive.google.com/file/d/1XPzd-pLeJC7jmCz5mKiSL1P1Fr0lsjpV/view?usp=drive_link",
    imgsrc: "https://i.pinimg.com/550x/39/16/03/3916034fdf1041b89b04be781701d854.jpg",
  },
];
export const videosample = [
  {
    id: "sam1",
    title: "Pre-Wedding ",
    des: "A pre-wedding short is a heartfelt and intimate video showcasing the couple's love story, special moments, and relationship leading up to the big day.",
    urlWithoutPlay: "https://www.youtube.com/embed/BQuclkte5rg",
    urlWithPlay: "https://www.youtube.com/embed/BQuclkte5rg?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "si=cbzQ3XjIqLUBLSCM",
    rating: "5",
  },
  {
    id: "sam2",
    title: "Wedding",
    des: "Uniting two souls in love, laughter, and happiness, celebrating a lifetime of togetherness and cherished moments.",
    urlWithoutPlay: "https://www.youtube.com/embed/w111G2kwFtQ",
    urlWithPlay: "https://www.youtube.com/embed/w111G2kwFtQ?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "agSOz0DsJjo?si=wswSQ6bhvbOMwdmS",
    rating: "4.9",

  },
  {
    id: "sam3",
    title: "Pre-Wedding",
    des: "A pre-wedding short: a romantic glimpse into the couple's love story before the big day.",
    urlWithoutPlay: "https://www.youtube.com/embed/dtQ23AhyKoQ",
    urlWithPlay: "https://www.youtube.com/embed/dtQ23AhyKoQ?autoplay=1&mute=0&cc_load_policy=1 si=5WEHdOu6QP_5WWvN",
    ytID: "si=5WEHdOu6QP_5WWvN",
    rating: "4.8",

  },
  {
    id: "sam4",
    title: "Highlights",
    des: "A romantic wedding video, with a captivating teaser and thrilling highlights.",
    urlWithoutPlay: "https://www.youtube.com/embed/86AuHB-st4c",
    urlWithPlay: "https://www.youtube.com/embed/86AuHB-st4c?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "si=gIYlpxbtjXP3a8xh",
    rating: "5",

  },
  {
    id: "sam5",
    title: "Teaser",
    des: "A glimpse of forever, love is coming soon, a heartwarming tale of two souls, a beautiful journey begins..",
    urlWithoutPlay: "https://www.youtube.com/embed/3uXcfstOuZ4",
    urlWithPlay: "https://www.youtube.com/embed/3uXcfstOuZ4?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "si=Nvw9NcfN51246G6d",
    rating: "4.2",

  },
  {
    id: "sam6",
    title: " Forever Captured",
    des: "Capturing the beauty of love, one frame at a time. A romantic journey of two hearts, forever in love",
    urlWithoutPlay: "https://www.youtube.com/embed/PKPgoXkfaXc",
    urlWithPlay: "https://www.youtube.com/embed/PKPgoXkfaXc?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "si=Rkv3GLGKEiZiJZpD",
    rating: "4.8",
  },

];
export const Slist = [
  {
    id: "Service1",
    imgsrc: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/518332246.jpg?k=852d9e83009ac082a7bb8366d5e27fb1f21801ea9cb6dde9c14e1aa99c49ea63&o=&hp=1",
    heading: "Hotels and Resorts",
    des: "Find the perfect venue with our curated selection of hotels and resorts. Enjoy luxury and comfort at competitive prices, ensuring a memorable experience for you and your guests without stretching your budget",
    Link: "/Hotel",

  },
  {
    id: "Service2",
    imgsrc: "https://www.carandbike.com/_next/image?url=https%3A%2F%2Fimages.carandbike.com%2Fcar-images%2Fbig%2Fhyundai%2Fcreta%2Fhyundai-creta.jpg%3Fv%3D92&w=3840&q=75",
    heading: "Car Services:",
    des: "Arrive in style with our premium car services, offering luxury and comfort at reasonable rates. Whether it’s a classic ride or a modern touch, we ensure a grand entrance for your special day",
    Link: "/Cars",
  },
  {
    id: "Service3",
    imgsrc: "https://5.imimg.com/data5/SELLER/Default/2021/5/KF/YW/UG/50200512/whatsapp-image-2021-05-31-at-11-43-49.jpeg",
    heading: "Decorations and Pandals",
    des: "Enchant your guests with our beautiful decorations and grand pandals. From elegant setups to lavish themes, we create unforgettable experiences at prices that suit your budget, adding charm to your celebration",
    Link: "/Decoratons",
  },
  {
    id: "Service4",
    imgsrc: "https://aaftonline.com/blog/wp-content/uploads/2024/01/What-are-the-Benefits-of-Photography-Complete-Overview.png",
    heading: "Photography",
    des: "Capture your magical moments with our expert photography services—every click tells your love story! We offer stunning photos at affordable prices, ensuring your memories are beautifully preserved without breaking the bank",
    Link: "/Photography",
  },
  {
    id: "Service5",
    imgsrc: "https://media.istockphoto.com/id/1349344078/vector/qr-code-scanning-scan-me-read-bar-code-mobility-generating-app-coding-recognition-or-reading.jpg?s=612x612&w=0&k=20&c=kFDiH2yOEXsvsbMrbVwEJ-GIKZaahEi5tXGWFjyFkog=",
    heading: "QR Code Designs:",
    des: "Revolutionize your invitations with our interactive QR code designs. Affordable, modern, and memorable—our designs offer a unique experience for your guests and seamless navigation to all wedding details",
    Link: "/qr",
  },
  {
    id: "Service6",
    imgsrc: "https://img.freepik.com/free-psd/wedding-invitation-greeting-cards-elegant-vintage-style_1340-49454.jpg",
    heading: "Wedding Invitation Cards",
    des: "Invite your guests in style with our elegant, customized wedding invitation cards. Designed to impress, our cards are both unique and budget-friendly, giving you quality without compromise",
    Link: "/cards",
  },
  {
    id: "Service7",
    imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPdDI9t7jX4b__BksCnLFWbpTRya8PFoUYrA&s",
    heading: "Elegant Courier Solutions",
    des: "Deliver your parcels with style using our elegant, customized courier packages. Designed to impress, our packaging solutions are both unique and budget-friendly, ensuring your items arrive safely without compromising on quality",
    Link: "/Courier",
  },
];
export const cardat = [
  {
    id: "Type1",
    link: "",
    title: "HONDA AMAZE",
    des: "₹1500",
    star: "4.8 🌟",
    rating: "(15 reviews)",
    path: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Honda/Amaze/10519/1689589132736/front-left-side-47.jpg"
  },
  {
    id: "Type2",
    link: "",
    title: "INNOVA CRYSTA ",
    des: "₹1500",
    star: "4.9 🌟",
    rating: "(12 reviews)",
    path: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Toyota/Innova-Crysta/9612/1697698611076/front-left-side-47.jpg"
  },
  {
    id: "Type3",
    link: "",
    title: "SWIFT DZIRE",
    des: "₹1000",
    star: "4.2 🌟",
    rating: "(22 reviews)",
    path: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Maruti/Swift-Dzire-Tour/8863/1717397917382/front-left-side-47.jpg"
  },
  {
    id: "Type4",
    link: "",
    title: "ERTIGA",
    des: "₹1200",
    star: "4.3 🌟",
    rating: "(15 reviews)",
    path: "https://content.carlelo.com/uploads/model/1668419592.webp"
  },
  {
    id: "Type5",
    link: "",
    title: "SCORPIO",
    des: "₹1400",
    star: "5 🌟",
    rating: "(30 reviews)",
    path: "https://images.91wheels.com/assets/c_images/gallery/mahindra/scorpio-classic/mahindra-scorpio-classic-3-1698085076.jpg?w=480&q=60?w=1080&q=60"

  },
  {
    id: "Type6",
    link: "",
    title: "DZIRE",
    des: "₹1100",
    star: "4.5 🌟",
    rating: "(13 reviews)",
    path: "https://images.carandbike.com/car-images/large/maruti-suzuki/dzire/maruti-suzuki-dzire.jpg?v=28"
  },
];
export const Hoteldet = [
  {
    id: "Hotel1",
    img1: "https://r2imghtlak.mmtcdn.com/r2-mmt-htl-image/htl-imgs/202009281848505371-5cf6d77e871e11eb8a5d0242ac110002.jpg",
    img2: "https://cdn.venuemonk.com/assets/kanpur/the-wedding-bells-kidwai-nagar/images/full/the-wedding-bells-kidwai-nagar-3086.jpg",
    img3: "https://i.ytimg.com/vi/hbjvuwIdfTs/maxresdefault.jpg",
    img4: "https://cdn0.weddingwire.in/vendor/4181/3_2/960/jpeg/banquet-hall-the-wedding-bells-banquet-hall-7_15_354181-160129138478066.jpeg",
    img5: "https://image.wedmegood.com/resized/800X/uploads/member/1242314/1620301781_20201122053402_IMG_2068.JPG",
    img6: "https://cdn0.weddingwire.in/vendor/4181/3_2/960/jpeg/banquet-hall-the-wedding-bells-banquet-hall-1_15_354181-160129136058385.jpeg",
    Hname: "THE WEDDING BELLS",
    Hdes: "The Wedding Bells Hotels & Resorts, offers travelers a heightened level of comfort, accommodation and safety.    The hotel itself offers services that are designed to offer maximum comfort to its guests. Accommodation at the  hotel is available in the well-appointed rooms, that are tastefully decorated and fitted with right amenities to   make the guest comfortable.",
    Rno: "250",
    Sno: "800",
    rate: "7.5",
    Are: "5000 sq ft",
    In: "Indoor",
    Out: "Outdoor",
    videos: [
      {
        id: "sa1",
        title: "Night View",
        des: "",
        urlWithoutPlay: "https://www.youtube.com/embed/OKSHx8_ufiw",
        urlWithPlay: "https://www.youtube.com/embed/OKSHx8_ufiw?autoplay=1&mute=0&cc_load_policy=1",
        ytID: "si=sEiYUm31NkwC7K_p",
        rating: "5",
      },
      {
        id: "sa2",
        title: "Over View of the Hotel",
        des: "",
        urlWithoutPlay: "https://www.youtube.com/embed/U7HRdd_cmm4",
        urlWithPlay: "https://www.youtube.com/embed/U7HRdd_cmm4?autoplay=1&mute=0&cc_load_policy=1",
        ytID: "si=iauf0YCptXQ1pwWK",
        rating: "4.9",
      },
    ]
  },
  {
    id: "Hotel2",
    img1: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/581818283.jpg?k=1b9f3a8d60b044fcf20e9c2ec3f5f802b87a27a4a22593e82875fd06f0875a7e&o=&hp=1",
    img2: "https://r1imghtlak.mmtcdn.com/2a41c1d4465811ef84b30a58a9feac02.jpg?&output-quality=75&downsize=520:350&crop=520:350;81,0&output-format=jpg",
    img3: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/581818367.jpg?k=05265d2cad0a83b10ed30148acc86744ecd2f4f832d99daec6ca3531b99f26ff&o=&hp=1",
    img4: "https://r1imghtlak.mmtcdn.com/65d5ab7a457711efa4bb0a58a9feac02.jpg?&output-quality=75&downsize=520:350&crop=520:350;81,0&output-format=jpg",
    img5: "https://r1imghtlak.mmtcdn.com/3039faca465811ef84b30a58a9feac02.jpg?&output-quality=75&downsize=520:350&crop=520:350;81,0&output-format=jpg",
    img6: "https://r1imghtlak.mmtcdn.com/43409174465811ef84b30a58a9feac02.jpg?&output-quality=75&downsize=520:350&crop=520:350;81,0&output-format=jpg",
    Hname: "THE VNR RESORT ",
    Hdes: "VNC Resort offers a blend of luxury and comfort, with modern amenities and spacious rooms. Whether for relaxation or adventure, it ensures an exceptional experience tailored to your needs.",
    Rno: "25",
    Sno: "500",
    rate: "3",
    Are: "5500 sq ft",
    In: "Indoor",
    Out: "Outdoor",
    videos: [
      {
        id: "sa3",
        title: "Night view",
        des: "Uniting two souls in love, laughter, and happiness, celebrating a lifetime of togetherness and cherished moments.",
        urlWithoutPlay: "https://www.youtube.com/embed/zy8gYoYyTiM",
        urlWithPlay: "https://www.youtube.com/embed/zy8gYoYyTiM?autoplay=1&mute=0&cc_load_policy=1",
        ytID: "si=fjLDvPAoWT2bcOo6",
        rating: "4.9",
      },
      {
        id: "sa4",
        title: "Over View of the Hotel",
        des: "Uniting two souls in love, laughter, and happiness, celebrating a lifetime of togetherness and cherished moments.",
        urlWithoutPlay: "https://www.youtube.com/embed/shH4Lb7Opmk",
        urlWithPlay: "https://www.youtube.com/embed/shH4Lb7Opmk?autoplay=1&mute=0&cc_load_policy=1",
        ytID: "si=qBGm4s9p82FY_zdn",
        rating: "4.9",
      },
    ]
  },
  {
    id: "Hotel3",
    img1: "https://gos3.ibcdn.com/e2f159ceb3d411ecbb520a58a9feac02.jpeg",
    img2: "https://images.oyoroomscdn.com/uploads/hotel_image/96742/large/guyojdusdaen.jpg",
    img3: "https://pix6.agoda.net/hotelImages/30434309/0/caf3fb3f98bef612b252dfe9e7700414.jpg",
    img4: "https://images.oyoroomscdn.com/uploads/hotel_image/96742/large/ynajtrsptjon.jpg",
    img5: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/175975098.jpg?k=14b53681b2033749eab5e277883c3a4cdc413f67585647c446e92657a50bd4c1&o=&hp=1",
    img6: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/109261140.jpg?k=b2f9a6027b68bd9cb75d7700ae75b0796151f587553a3bc015497f301c3e2caa&o=&hp=1",
    Hname: "THE YAMUNA HOTEL",
    Hdes: "The Yamuna Hotel in Dhanbad is known for its comfortable accommodations and convenient location. It typically offers amenities such as well-furnished rooms, in-house dining, and modern facilities to cater to both business and leisure travelers. For specific details like pricing, services, and reviews, you might want to check recent customer feedback or the hotel's official website.",
    Rno: "8",
    Sno: "500",
    rate: "1.5",
    Are: "4500 sq ft",
    In: "Indoor",
    Out: "Outdoor",
    videos: [
      {
        id: "sa5",
        title: "Wedding",
        des: "Uniting two souls in love, laughter, and happiness, celebrating a lifetime of togetherness and cherished moments.",
        urlWithoutPlay: "https://www.youtube.com/embed/shH4Lb7Opmk",
        urlWithPlay: "https://www.youtube.com/embed/shH4Lb7Opmk?autoplay=1&mute=0&cc_load_policy=1",
        ytID: "si=qBGm4s9p82FY_zdn",
        rating: "4.9",
      },
      {
        id: "sa6",
        title: "Wedding",
        des: "Uniting two souls in love, laughter, and happiness, celebrating a lifetime of togetherness and cherished moments.",
        urlWithoutPlay: "https://www.youtube.com/embed/X2-o8bjuigc",
        urlWithPlay: "https://www.youtube.com/embed/X2-o8bjuigc?autoplay=1&mute=0&cc_load_policy=1",
        ytID: "si=HQNobK0G09ZwwwhK",
        rating: "4.9",
      },
    ]
  },

];
// export const photoinfodetails = [

//   {
//     id: 1,
//     title: "TRdtional",
//     type: "A",
//     price: "600",
//     img1: "",
//     img2: "",
//     img3: "",
//     img4: "",
//     img5: "",
//     event1: "MD IRAN",
//     camera1: "eee",
//     camera2: "ddd",
//     event2: "uuu",
//     people1: "dd",
//     people2: "ddd",
//     extra: "ddd",
//     album1: "dd",
//     album2: "dd",
//     img6: "",
//     img7: "",
//     img8: "",
//     img9: "",
//     img10: "",
//     linkal: "",
//   },
//   {
//     id: 2,
//     title: "cinematic",
//     type: "akao",
//     price: "ddjs",
//     img1: "",
//     img2: "",
//     img3: "",
//     img4: "",
//     img5: "",
//     event1: "",
//     camera1: "",
//     camera2: "",
//     event2: "",
//     people1: "",
//     people2: "",
//     extra: "",
//     album1: "",
//     album2: "",
//     img6: "",
//     img7: "",
//     img8: "",
//     img9: "",
//     img10: "",
//     linkal: "",
//   },
//   {
//     id: 3,
//     title: "333",
//     type: "",
//     price: "",
//     img1: "",
//     img2: "",
//     img3: "",
//     img4: "",
//     img5: "",
//     event1: "",
//     camera1: "",
//     camera2: "",
//     event2: "",
//     people1: "",
//     people2: "",
//     extra: "",
//     album1: "",
//     album2: "",
//     img6: "",
//     img7: "",
//     img8: "",
//     img9: "",
//     img10: "",
//     linkal: "",
//   },
//   {
//     id: 4,
//     title: "444",
//     type: "",
//     price: "",
//     img1: "",
//     img2: "",
//     img3: "",
//     img4: "",
//     img5: "",
//     event1: "",
//     camera1: "",
//     camera2: "",
//     event2: "",
//     people1: "",
//     people2: "",
//     extra: "",
//     album1: "",
//     album2: "",
//     img6: "",
//     img7: "",
//     img8: "",
//     img9: "",
//     img10: "",
//     linkal: "",
//   },
//   {
//     id: 5,
//     title: "666",
//     type: "",
//     price: "",
//     img1: "",
//     img2: "",
//     img3: "",
//     img4: "",
//     img5: "",
//     event1: "",
//     camera1: "",
//     camera2: "",
//     event2: "",
//     people1: "",
//     people2: "",
//     extra: "",
//     album1: "",
//     album2: "",
//     img6: "",
//     img7: "",
//     img8: "",
//     img9: "",
//     img10: "",
//     linkal: "",
//   },
//   {
//     id: 6,
//     title: "",
//     type: "",
//     price: "",
//     img1: "",
//     img2: "",
//     img3: "",
//     img4: "",
//     img5: "",
//     event1: "",
//     camera1: "",
//     camera2: "",
//     event2: "",
//     people1: "",
//     people2: "",
//     extra: "",
//     album1: "",
//     album2: "",
//     img6: "",
//     img7: "",
//     img8: "",
//     img9: "",
//     img10: "",
//     linkal: "",
//   },
//   {
//     id: 7,
//     title: "",
//     type: "",
//     price: "",
//     img1: "",
//     img2: "",
//     img3: "",
//     img4: "",
//     img5: "",
//     event1: "",
//     camera1: "",
//     camera2: "",
//     event2: "",
//     people1: "",
//     people2: "",
//     extra: "",
//     album1: "",
//     album2: "",
//     img6: "",
//     img7: "",
//     img8: "",
//     img9: "",
//     img10: "",
//     linkal: "",
//   },
//   {
//     id: 8,
//     title: "",
//     type: "",
//     price: "",
//     img1: "",
//     img2: "",
//     img3: "",
//     img4: "",
//     img5: "",
//     event1: "",
//     camera1: "",
//     camera2: "",
//     event2: "",
//     people1: "",
//     people2: "",
//     extra: "",
//     album1: "",
//     album2: "",
//     img6: "",
//     img7: "",
//     img8: "",
//     img9: "",
//     img10: "",
//     linkal: "",
//   },
//   {
//     id: 9,
//     title: "",
//     type: "",
//     price: "",
//     img1: "",
//     img2: "",
//     img3: "",
//     img4: "",
//     img5: "",
//     event1: "",
//     camera1: "",
//     camera2: "",
//     event2: "",
//     people1: "",
//     people2: "",
//     extra: "",
//     album1: "",
//     album2: "",
//     img6: "",
//     img7: "",
//     img8: "",
//     img9: "",
//     img10: "",
//     linkal: "",
//   },
// ];
export const faq = [
  {
    id: "q1",
    ques: "What are QR cards? ",
    ans: "QR cards are digital invitations that include a QR code. Guests can scan the QR code with their smartphones to access the event details, RSVP, and other information online.",
  },
  {
    id: "q2",
    ques: "How do QR cards work? ",
    ans: "After we design your card, we generate a unique QR code that links to your event page. Guests scan this code to view all the details.",
  },
  {
    id: "q3",
    ques: "How do I customize my QR card? ",
    ans: "You can use our online design tool to customize your card with your chosen text, colors, and images",
  },
  {
    id: "q4",
    ques: "2.	Can I upload my own design? ",
    ans: "Yes, you can upload your own design, and we will integrate the QR code into it.",
  },
  {
    id: "q5",
    ques: "3.	What information can I include in the QR code?",
    ans: "You can include details like the event date, time, location, RSVP link, and any special instructions.",
  },
  {
    id: "q6",
    ques: "4.	Can I add my wedding or event website link to the QR card? ",
    ans: "Yes, you can include your personal wedding or event website link in the QR code.",
  },
  {
    id: "q7",
    ques: "1.	What are your pricing options? ",
    ans: "Our pricing depends on the complexity of the design and the number of cards you order. Please refer to our pricing page for detailed information.",
  },
  {
    id: "q8",
    ques: "2.	What payment methods do you accept? ",
    ans: "We accept major  online payment methods.",
  },
  {
    id: "q9",
    ques: "1.	How long does it take to receive my QR card? ",
    ans: "? Digital QR cards are delivered instantly via email. If you opt for physical cards, delivery times vary based on your location.",
  },
];

export const menuOptions = [
  {
    opt: "HOME",
    route: "/",
  },
  {
    opt: "SERVICE",
    route: "/Service",
  },
  {
    opt: "CARDS",
    route: "/cards",
  },
  {
    opt: "VIDEO",
    route: "/videos",
  },
  {
    opt: "QR DESIGN",
    route: "/qr",
  },
  {
    opt: "PHOTOGRAPHY",
    route: "/photography",
  },
  {
    opt: "CONTACT US",
    route: "/contact",
  },
];

export const hoverShadowColors = [
  " hover:shadow-purple-600",
  " hover:shadow-fuchsia-600",
  " hover:shadow-cyan-600",
  " hover:shadow-teal-600",
  " hover:shadow-amber-600",
  " hover:shadow-orange-600",
  " hover:shadow-gray-600",
  " hover:shadow-slate-600",
  " hover:shadow-red-600",
  " hover:shadow-blue-600",
  " hover:shadow-green-600",
  " hover:shadow-pink-600",
  " hover:shadow-lime-600",
  " hover:shadow-indigo-600",
  " hover:shadow-sky-600",
  " hover:shadow-yellow-600",
  "hover:shadow-emerald-600",
];
export default cardat;

